### ISSUE TITLE
Release Needed

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-collector#1034]
With the large restructuring of code and [the recent update of the vanity URLs](https://github.com/open-telemetry/opentelemetry-go-vanityurls/pull/3) to support this import path imports are now broken without intervention. E.g.

```
go.opentelemetry.io/collector/consumer/consumerdata: go.opentelemetry.io/collector@v0.3.0: parsing go.mod:
module declares its path as: github.com/open-telemetry/opentelemetry-collector
        but was required as: go.opentelemetry.io/collector
```

Additionally, if you try building against packages that are in master but not in the v0.3.0 release (i.e. `go.opentelemetry.io/collector/consumer/pdata`), the build will fail. The only way around this is to explicitly update your `go.mod` to depend on a git commit.

Making a release > v0.3.0 will resolve this issue. It looks like, in addition to including all the changed code (i.e. adding `consumer/pdata`), it also has updated `go.mod` to the new import path.

**Comment by tigrannajaryan** [comment]
We are planning a release in 1-2 weeks. We want to beef up the test suite and spend more time testing in our internal environments to gain more confidence we did not break the Collector due to the large volume of changes.

Issues to track (we probably won't do them all right now):
https://github.com/open-telemetry/opentelemetry-collector/issues/1022
https://github.com/open-telemetry/opentelemetry-collector/issues/1023
https://github.com/open-telemetry/opentelemetry-collector/issues/1024
https://github.com/open-telemetry/opentelemetry-collector/issues/1025
https://github.com/open-telemetry/opentelemetry-collector/issues/1026
https://github.com/open-telemetry/opentelemetry-collector/issues/1027
https://github.com/open-telemetry/opentelemetry-collector/issues/1028
https://github.com/open-telemetry/opentelemetry-collector/issues/1029
https://github.com/open-telemetry/opentelemetry-collector/issues/1030
https://github.com/open-telemetry/opentelemetry-collector/issues/1031

Help is appreciated.

**Comment by jrcamp** [comment]
@tigrannajaryan might help to track these with Github milestones (https://github.com/open-telemetry/opentelemetry-collector/milestones).

**Comment by tigrannajaryan** [comment]
Tracking in milestone https://github.com/open-telemetry/opentelemetry-collector/milestone/4

**Comment by flands** [comment]
0.4.0 released!
