### ISSUE TITLE
[exporterhelper] Awkwardness due to API between queue sender and batch sender

### ISSUE THREAD

**Issue by carsonip** [open-telemetry/opentelemetry-collector#10368]
**Is your feature request related to a problem? Please describe.**

Related to batch sender in #8122 

Currently, queue sender and batch sender work together fine, but the config `sending_queue.num_consumers` and batch sender `concurrencyLimit` make it a little awkward to use. The awkwardness comes from the fact that it is impossible for batch sender to get more requests than queue sender's num_consumers, and may be forced to export a smaller batch due to it.

I am also not sure if this presents a performance problem at scale, which means a lot of goroutines will be involved.

The batch sender concurrency check has also been prone to unfavorable goroutine scheduling, as reported in #9952 .

**Describe the solution you'd like**

Ideally, queue sender can keep sending to batch sender without an artificial limit, such that batching is only triggered by min_size_items and flush_timeout.

I don't have an idea how to implement this yet. Also, this may require a change in contract between exporterhelper parts.

**Comment by jmacd** [comment]
@moh-osman3 and I studied the same problem -- we want to avoid use of a queue_sender but we want concurrency in the batcher. I reason that another user will come along asking not to use the queue sender, not to use the batch sender, and still want concurrency. Therefore, I propose we try to (and @moh-osman3 has been investigating how to) add a new sender stage purely for concurrency control.

In such a future, the existing queue_sender num_consumers I think should dictate how many workers perform the cpu and I/O intensive work of gathering items from the queue, not dictate how many export threads are used.

**Comment by moh-osman3** [comment]
@dmitryax @carsonip This PR https://github.com/open-telemetry/opentelemetry-collector/pull/10478 shows an implementation of the concurrency_sender which will limit the number of goroutines used for export. This removes the concurrenyLimit from the batch_sender so that batch exports are only triggered by size/timeout and the concurrency is limited by the new sender independent of queue_sender.num_consumers. Any thoughts on this approach?

**Comment by dmitryax** [comment]
@jmacd just wanted to clarify that the existing implementation is concurrent. This issue is about limiting concurrency

**Comment by dmitryax** [comment]
I believe the solution should to change API interface between queue and batch from pushing queue->batcher to pulling queue<-batcher. So if queue and batcher are enabled, we treat batcher as queue consumers.  The number of concurrent batchers should be configurable, similar to queue consumers it'll represent the maximum amount of outgoing requests.

The workflow would be the following:
1. Pick a batcher/consumer from the pool, make it an active batcher
1. The active batcher picks items from the queue until the minimum batch size (or flush timeout) is reached
1. The batcher sends the data and marks itself as busy. Once the request is completed, the batcher puts itself back in the pool
1. Repeat 1-3 steps while there are available batcher/consumer in the pool. Otherwise, wait

**Comment by axw** [comment]
@dmitryax that sounds good to me. I wrote down related thoughts at https://github.com/open-telemetry/opentelemetry-collector/pull/10478#discussion_r1687319594.

Re `num_workers` config: too few workers and we may not achieve optimal throughput, too many workers and we may never reach the minimum batch size. I think starting with configurable `num_workers` is the way to go, but it might be worth later adding auto scaling based on queue depth.

**Comment by dmitryax** [comment]
> too many workers and we may never reach the minimum batch size. 

`num_workers` doesn't affect this. Only one active batcher can consume metrics from the queue until the batch is ready to be exported. Other batchers are either `inactive` in the pool or `busy` sending completed batches.

**Comment by dmitryax** [comment]
I think we can start with the same default value for the `num_workers` as queue has: `10`

**Comment by axw** [comment]
> num_workers doesn't affect this. Only one active batcher can consume metrics from the queue until the batch is ready to be exported. Other batchers are either inactive in the pool or busy sending completed batches.

Ah ok, I understand now. Sounds good.

FWIW we took that approach in an earlier version of Elastic APM and then switched to having multiple concurrently polling queue consumers to make better use of CPUs. It may not be relevant here, since in that case the queue consumer was doing more CPU-heavy work (JSON document encoding) than the batcher would be doing. (And the reason we did it there was so the bytes-based threshold could be based on the compressed total encoded documents size.)

**Comment by moh-osman3** [comment]
> `num_workers` doesn't affect this. Only one active batcher can consume metrics from the queue until the batch is ready to be exported. Other batchers are either `inactive` in the pool or `busy` sending completed batches.

Hmm why can we only have one active batcher? Why shouldn't all batchers read from the queue and try to form batches?

**Comment by dmitryax** [comment]
> Hmm why can we only have one active batcher? Why shouldn't all batchers read from the queue and try to form batches?

Because we can't get consistent batching in that case. Let's say we have 200 items in the queue, and the minimum batch side is configured to be 100. The expected behavior is to get 2 batches of 100 items each sent out right away. However, if we have, let's say, 4 batchers reading from the queue concurrently, they can get smaller batches like 50,50,50,50 and be blocked until the timeout is reached. Once the timeout is passed, they will send 4x50 batches. Not ideal.

**Comment by dmitryax** [comment]
@sfc-gh-sili is currently helping with this issue. She prepared a design doc based on our discussions: https://docs.google.com/document/d/1y5jt7bQ6HWt04MntF8CjUwMBBeNiJs2gV4uUZfJjAsE/edit#heading=h.ypo1293baglx Feel free to take a look and comment

**Comment by carsonip** [comment]
@dmitryax @sfc-gh-sili Thanks for the design doc, it looks good at a high level. Moving batching into queue sender when sending queue is enabled makes sense to me, and it should fix the awkwardness described in this issue, despite a little bit of extra complexity to handle both sending_queue={false,true}. I am happy to review the PRs when they are ready.
