### ISSUE TITLE
Add "Relation" as new Observability category

### ISSUE THREAD

**Issue by fredyfredburger** [open-telemetry/opentelemetry-collector#10374]
**Priority Note**
I don't think this feature should be prioritized over a 1.0 release.  I'm asking for this to be considered and debated for future inclusion, as I think there is a lot of value to be had by extending the observability umbrella to include relation-type data at the same level as logs, traces, and metrics.

**Is your feature request related to a problem? Please describe.**
There is a category of observability data that is not currently supported by OpenTelemetry.  Relational data, such as the result of the netstat Go library, does not fit cleanly into metrics, logs, or traces.  This would enable better data structures to capture that branch of observability and would make it easier to build pipelines to put the data in graph databases.

**Describe the solution you'd like**

Addition of "relation" to the same set as "logs, traces, metrics", including creating a new data structure, ability to create relation pipelines.  This would mean adding an entire new API for relation data.

**Describe alternatives you've considered**
It could be argued that, "relations are just a metric, where key is the relation and the value is the count of times observed" - but that description really shoe-horns the data into a poorly fit data structure, making it harder to get use from the data on the back-end.  This data would more cleanly fit in an edge-node structure.  An example using netstat: (host ip) -{tcp TIME_WAIT port:port}-> (remote ip)

**Additional context**
The primary use case I see for this data is not observability into applications.  Instead, my primary concern is for network security, network monitoring, and system administration.  However, if a relational data type was added to OpenTelemetry, I don't doubt the number of use cases would grow as people realized the flexibility of making relationships observable.

**Comment by mx-psi** [comment]
Hi @fredyfredburger, thanks for your issue! You may be interested in reading the [entities data model proposal](https://github.com/open-telemetry/oteps/blob/main/text/entities/0256-entities-data-model.md). This is a new signal type that aims to represent entities such as hosts, containers, pods... and the relations between them. I am honestly not sure if your use case is something that is being kept in mind for this signal type, but I think it would be the first place to check this.

You can contact the group that is working on this by searching for "Specification: Entities" on the [community repository](https://github.com/open-telemetry/community?tab=readme-ov-file#specification-sigs).

Since this repository is for OpenTelemetry Collector issues only and this would need to be defined at the data model first, I am going to close this as wontfix, but I hope the information above helps you reach out to the right set of people :)

**Comment by fredyfredburger** [comment]
Oh, that's perfect - thank you!  Specifically, this line here is what I'm looking for, but it makes sense that entities would come first: "Note: subsequent OTEPs will define how the entities are associated with traces, metrics and logs and how relations between entities will be specified. See [Future Work](https://github.com/open-telemetry/oteps/blob/main/text/entities/0256-entities-data-model.md#future-work)." - from [entities data model proposal](https://github.com/open-telemetry/oteps/blob/main/text/entities/0256-entities-data-model.md)
