### ISSUE TITLE
Review metadata.yaml units for internal telemetry: `cmd/mdatagen/testdata`

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#10654]

**Comment by crobert-1** [comment]
The only generic "1" unit type is [here](https://github.com/open-telemetry/opentelemetry-collector/blob/7d5b1ba387e4e171e25bfeea9b70d6fdfbe08fab/cmd/mdatagen/testdata/no_type_attr.yaml#L20). This is a test data file used to ensure that the proper error is returned when a `metadata.yaml` attribute does not have a type.

Since the metric is for testing and exists just as a filler value to test something unrelated, I think we can close this issue and leave the unit as-is.

**Comment by codeboten** [comment]
@crobert-1 sounds good
