### ISSUE TITLE
[configtelemetry] Remove it?

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#11027]
Personal opinion, I would try first to completely remove this module instead of making it stable. Why?
* Otel doesn't have a concept of telemetry level and us in otel-collector inventing this is not the right thing.
* This concept was added to control "expensive" telemetry (more exactly only metrics), but that can be now controlled with views.

_Originally posted by @bogdandrutu in https://github.com/open-telemetry/opentelemetry-collector/issues/11002#issuecomment-2322504322_

**Comment by mx-psi** [comment]
Putting this into a release:blocker issue to avoid releasing the module if we don't want to

**Comment by TylerHelmuth** [comment]
Both points are valid, but based on the discussions we had previously around this feature the benefits outweighed the downside of us define the concept. They were:

1. Views are hard for end-users to comprehend and implement. Additionally, introducing the concept of levels for metrics does not prevent the end user from using views if they want to.
2. We've already had metric level in place for a long time and users are using it.

We've also updated mdatagen so that all components within our control document their own telemetry and under which metric level the metrics is emitted: https://github.com/open-telemetry/opentelemetry-collector/blob/15542e67e1346a87273a8c83c7f44582eab3874e/processor/batchprocessor/metadata.yaml#L12-L50.

I feel this is a time that it is beneficial to deviate from the spec to help our end users.
