### ISSUE TITLE
Unnecessary high memory in sharedcomponent

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#11818]
The https://github.com/open-telemetry/opentelemetry-collector/pull/10777 added the "capability" to keep all previously reported events in shared components and the list grows unbounded causing memory issues.

Proposed solution: only preserve the last reported event.

**Comment by TylerHelmuth** [comment]
For an status aggregator I believe it is important that the previous events be played back in order. Since `SharedComponent` is internal and we control how it is used, and since we only ever add sources during startup, I suggest a circular buffer with a small size.  This allows us to replay all the events during startup, but then during normal operation, once we are done adding sources, we won't have to remember every event we've ever sent.
