### ISSUE TITLE
Unsplit the OTLP receiver protocols, use a shared port

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-collector#1256]
**Is your feature request related to a problem? Please describe.**
This is a request to revert https://github.com/open-telemetry/opentelemetry-collector/pull/1223

**Describe the solution you'd like**
I would like both protocols to share a port, as this reduces configuration cost for users and system operators.

**Describe alternatives you've considered**
The alternative is to use a single port. The PR https://github.com/open-telemetry/opentelemetry-collector/pull/1223 did not provide a good justification for this change.

**Additional context**
At LightStep we once had a multi-port satellite, and it was a huge problem for our users. We eventually were able to support a single-port configuration with both gRPC and HTTP, secure and insecure settings.

**Comment by austinlparker** [comment]
Mostly just echoing Josh's comment here. Multi-port satellites caused us no end of headaches for users.

**Comment by bogdandrutu** [comment]
@jmacd happy to revert if you show me how to make TLS work with port multiplexing.

**Comment by jmacd** [comment]
I'm asking around Lightstep for someone who can contribute here. Thanks.

**Comment by jpkrohling** [comment]
For context, #1227 might have been the reason for the change.

**Comment by jmacd** [comment]
Just want to repeat that "no end of headaches for users" is not an exaggeration. It was an awful time. I'm looking for someone to help on this.

**Comment by MatthewDolan** [comment]
@bogdandrutu Can you expand more on what about TLS needs to work to make this port viable?

**Comment by MatthewDolan** [comment]
I think there recommendation from grpc-go for supporting both http and grpc on the same port is to utilize the `ServerHTTP(...)` method on the grpc server.

https://godoc.org/google.golang.org/grpc#Server.ServeHTTP

Something similar to the example code in the docs:

```
if r.ProtoMajor == 2 && strings.HasPrefix(r.Header.Get("Content-Type"), "application/grpc") {
	grpcServer.ServeHTTP(w, r)
} else {
	httpMux.ServeHTTP(w, r)
}
```

The TLS support needs to be handled at the http layer because the request has to be decrypted before it can be routed to either the grpc or http mux.

@bogdandrutu, is that the information you were looking for? Apologies if I am missing context from another thread.

**Comment by bogdandrutu** [comment]
@jmacd can you please tell me if all protocols are enabled or you still want user to configure which protocols to enable?

**Comment by tcolgate** [comment]
I would say that the operational overhead of two ports is worth it for the simpler code. I previously attempted to add full mutual tls to OTel collector but failed due to issues with cmux. They may have been resolvable, but the port sharing made debugging quite painful.

**Comment by tcolgate** [comment]
FWIW, the grpc server.ServeHTTP() http.Handler approach has worked better for me, but that ends up mandating a http2/https client, which may not be acceptable. It is also less performant that the cmux approach, acceptable for a lot of use cases, but possible not if you are getting a lot of small requests (probably OK for streaming though).

**Comment by jpkrohling** [comment]
> but the port sharing made debugging quite painful

I think this alone is worth having two ports. At least, we *know* what each port is supposed to be receiving.

> acceptable for a lot of use cases, but possible not if you are getting a lot of small requests

I'd like to echo this point. Having a performance compromise on the receiver end sounds like a bad idea, especially if there's no workaround or option to disable this compromise.

**Comment by jmacd** [comment]
I don't intend to contest any decisions here. LightStep's experience with configuring SDKs, firewalls, and ingress rules for multi-port collectors is still a painful memory.

**Comment by jpkrohling** [comment]
@jmacd I really appreciate your experience, and I think it would be easier for us all to understand the problems you had if you gave some concrete examples. We could then compare both problems and see which poison we want to take.

**Comment by austinlparker** [comment]
The biggest things off the top of my head...
- It's a nightmare for users who are instrumenting things, because now they need to know more than one port number
- You need to do something different depending on _where_ your service is running (am I inside the dc/vpc? outside?), which adds another thing for people to keep in mind.
- Multiple ports make sane defaults harder, because your default and my default might need to be different rather than having a single well-known port.
- Operators need to remap ports and configure load balancing (with multiple transports!) rather than using a single TCP load balancer _or_ if they want single port operation they'll need to do more fancy LB configuration... again, it's just extra setup steps.

I'm compiling some more horror stories, I'll post 'em when I got 'em.

**Comment by tcolgate** [comment]
@austinlparker I've had experience with the network ops side of these things, I've felt the paiin. What I would say though, for me, being unable to support mutual TLS would be a show stopper, especially for the client -> agent -> collector communication, agent -> collector in particular. (sorry if the terminology is incorrect for OTel).
  It's also worth saying that, if you are doing inter-service mTLS, then it becomes more likely that the http are potentially serving different functions, so might need different creds for those purposes, and in that case, having the separate ports, and config for the separate, makes the configuration much easier to understand.

**Comment by jpkrohling** [comment]
If we decide to go with a single port for both protocols for v1.0, changing it later to individual ports would probably be a breaking change. Going with individual ports for v1.0 and changing it later to a single port would not be a breaking change, unless I'm missing something.

Here's my suggestion: let's have them separated in the configuration, each with its own host-port/TLS options. If post-GA we decide that the operational headaches are indeed affecting a good number of users (which I think it really might), we can add an option for people to have both protocols in the same port, given the right conditions:

1. at most one of TLS options are set
1. at most one of the host-ports are set
1. (optional) a new `combine-ports` option is set

**Comment by tcolgate** [comment]
> The alternative is to use a single port. The PR #1223 did not provide a good justification for this change.

#1223 did explicitly state you can't do mTLS with cmux, which has also been my experience (I added the mTLS support to thanos and jaeger, but failed on otel, and have previous experience with cmux projects, I also spent a good few days on the otel attempt).

**Comment by austinlparker** [comment]
I'll also present the opposite side of my own argument, for context - while we _did_ have these problems, many of them were due to the fact that Lightstep supported (and continues to support) a _lot_ of transports to our satellite (I believe we accept 8 discrete transport formats at this point?), and a lot of the configuration confusion was specifically around people that were implementing polyglot tracing deployments using client libraries that may have only supported one or two out of several different wire formats, so you'd have a situation where the port used for ruby was different than the port used for java and those were both different than iOS ports, etc. etc.

I don't think it's unreasonable to suggest that future collector receivers could lead us to a place where similar situations occur. In a couple of years, I can easily imagine a world where a collector exists that accepts New Relic, Datadog, Jaeger, Zipkin, SFX, Stackdriver, AppInsights, Honeycomb, Lightstep, OTLP, etc... and each of _those_ potentially having its own set of secure/insecure ports. That's not a problem we can solve right now, but it's a problem that we should at least be mindful of, because as much as I'd like to pretend we're going to solve all the worlds problems with OTLP, I think there's enough 'legacy' protocols out there that receiver proliferation will cause really intense config pain for operators down the line.

That said, I think @jpkrohling suggestion of an optional combined port solution for users who wish to have it isn't a bad one - I think if we can at least hold the line on a "default configuration of least surprise" then we'll ease the adoption curve.

**Comment by jpkrohling** [comment]
> default configuration of least surprise

I like that :-)

**Comment by tigrannajaryan** [comment]
@bogdandrutu assigning to you to either implement the shared port or close it as "won't do". We need the decision for 1.0.

**Comment by axw** [comment]
https://github.com/elastic/gmux may be useful. Excerpt:

> gmux is a Go library for simultaneously serving net/http and gRPC requests on a single port.
>
> gmux is derived from cmux, enabling mTLS at the expense of reduced flexibility. Whereas cmux operates at the transport layer and enables multiplexing arbitrary application layer protocols, gmux operates at the application layer (on top of HTTP with or without TLS), to enable better integration with net/http and crypto/tls.

It's quite new code, so bugs may not yet have been all shaken out.

**Comment by jpkrohling** [comment]
> It's quite new code, so bugs may not yet have been all shaken out.

I'd go with the safe solution for v1 (each protocol in its own port), and offer a `combine-ports` option that could use this.

**Comment by tonglil** [comment]
I'm coming to this as a new user, just to add to add a few points for using split ports:

Users need to know more than one port number, but it's kind of the nature of a collector w/ multiple receivers. It wasn't hard to configure multiple ports, but know that the difficulty in tracking these numbers is because:

1. the defaults are not documented (or docs use legacy ports)
2. the defaults are not printed out by the collector (ie the opencensus receiver doesn't say which port it's using)
3. the log messages are very busy and the port numbers are hidden in there somewhere

If the docs were clear about what ports are used by these receivers, it would have been easier.

These should be fixed or improved for going GA.

---

I actually desire an explicit distinction between gRPC and HTTP.

One example is that in the OpenCensus receiver, it listens to both gRPC and http on the same port (even though it's broken right now). I want to actually turn off/block HTTP traffic to the receiver, and that's not really possible right now AFAICT.

This is because I am exposing the collector publicly (to listen for traces from serverless sources) and requiring mTLS, which OC's HTTP ocagent and OTel's OC receiver do not support.

In this case, separating the ports will let me turn off an insecure connection.

---

The best of both worlds is as mentioned:
> an optional combined port solution for users who wish to have it

Although my first question as a new user is: why I would want this at all? It just seems more complicated than necessary. FWIW my bias is towards being explicit.

**Comment by jmacd** [comment]
At Lightstep we eventually discovered technical difficulties with the single-port setup that we have been using. There is a grpc2http upgrade path that we feel is not reliable for use at this time and have given up attempting to use single-port support.
