### ISSUE TITLE
Migrate Tail Sampling Processor to the new OTLP-based internal data model

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#1306]
**Is your feature request related to a problem? Please describe.**
Tail Sampling Processor uses old OpenCensus data model which causes unnecessary translations to OC format.

**Describe the solution you'd like**
Tail Sampling Processor should use OTLP-based internal data model (consumer/pdata/trace.go) instead of OC.

**Comment by vikrambe** [comment]
@dmitryax i can chime in here

**Comment by dmitryax** [comment]
Thanks!

**Comment by dmitryax** [comment]
Hi @vikrambe did you have a chance to take a look into this ticket or https://github.com/open-telemetry/opentelemetry-collector/issues/1305 ?

**Comment by vikrambe** [comment]
@dmitryax @bogdandrutu  I have created a PR for #1305

Its been ages since i submitted a PR [https://github.com/open-telemetry/opentelemetry-collector/pull/1251] for tail sampling composite policy its still not reviewed, Anyways, even that PR would need a change to use otlp model. Can i also include composite changes as part of this issue ? Please, suggest ?

**Comment by vikrambe** [comment]
@dmitryax FYI...  I have started working on this, i will open a PR in next few days

**Comment by dmitryax** [comment]
@vikrambe nice! thanks for letting us know

**Comment by vikrambe** [comment]
@dmitryax : I have opened a PR. Sorry for the delay, was stuck with other priorities.

**Comment by vikrambe** [comment]
@jpkrohling @tigrannajaryan @asldevi FYI...

**Comment by dmitryax** [comment]
Awesome! Thank you

**Comment by bogdandrutu** [comment]
Processor moved
