### ISSUE TITLE
Add helm chart to deploy collector into Kubernetes

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-collector#1490]
**Is your feature request related to a problem? Please describe.**

Deploy opentelemetry-collector into Kubernetes and allow easy integrations with other helm chart based installers.

**Describe the solution you'd like**

OTEL collector helm chart. 

**Describe alternatives you've considered**

Use the https://github.com/open-telemetry/opentelemetry-operator, however it is not convenient in pure helm environments.

**Additional context**

None.

**Comment by pavolloffay** [comment]
We should decide whether it will be versioned in this repository or in a separate like the operator. 

I can submit a PR.

**Comment by mikelorant** [comment]
I have implemented a Helm chart for `opentelemetry-operator`. I have also created a Helm chart that creates a resource for `OpenTelelemetryCollector` which is acted on by the operator.

https://github.com/fairfaxmedia/charts/tree/master/stable/opentelemetry-operator
https://github.com/fairfaxmedia/charts/tree/master/stable/opentelemetrycollector

This I feel is a better result than directly creating a chart for the `collector` itself.

**Comment by genebean** [comment]
I have written a helm chart for our internal deployment of the collector and would be happy to contribute it if desired.

**Comment by mikelorant** [comment]
@genebean Would it be worthwhile comparing what we have and seeing if we can combine them?

**Comment by genebean** [comment]
I'd be game for that. I think it could be fairly easy to make it so the chart would work standalone or as part of the operator. If that sounds practical to you, I will work up a PR for your repo.

**Comment by mikelorant** [comment]
Have a look at my approach and see if it suits you. I based it some very specific needs so it might not work well for others. I mostly wanted to be able to generate the collector config from layered values files. Didn't work as well as I hoped due to how Helm handles empty keys.

I allowed the operator to be able to define a collector config or be able to use another chart to put down the collector CRD. This I think worked quite well even though the operator still needs a lot more work to get to a mature status.

May I ask why you decided to use the collector directly rather than the operator?

**Comment by genebean** [comment]
Honestly... because I had no idea the operator was a thing. It didn't show up in any of the places I looked. Also, I don't actually see what the operator give me here as this is not a complicated deployment.

**Comment by genebean** [comment]
I will also take a more detailed look at the operator though and make sure that it isn't a better fit for us

**Comment by flands** [comment]
https://github.com/open-telemetry/opentelemetry-helm-charts exists now with a helm -- please open issues / contribute there
