### ISSUE TITLE
Review TLS support for OC receiver and add tests

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#170]
TLS config for OC receiver is being added via #167 however in light of https://github.com/census-instrumentation/opencensus-service/issues/596 I think we need to revisit the implementation and tests here.

**Comment by ccaraman** [comment]
@pjanotti I would like to take this one since I'm working on improving oc receiver documentation and test coverage!

**Comment by pjanotti** [comment]
The code used here should be shared with fix for #126 - more general gRPC configuration settings seem shareable with other gRPC receivers and exporters

**Comment by annanay25** [comment]
@pjanotti +1

This chunk of code for generating grpc calloptions from the common `grpcsettings` can also be moved to common, so all exporters/receivers can share? - https://github.com/open-telemetry/opentelemetry-service/blob/63362d5eca860948fe70f79678619ab43ea6fd5b/exporter/opencensusexporter/factory.go#L73-L81

**Comment by bogdandrutu** [comment]
I think we now have ConfigGrpc that has all of these things.

**Comment by tonglil** [comment]
Hello, can I ask if anyone has tested or gotten an OpenCensus instrumented application using the `ocagent` exporter to send to a OpenTelemetry collector configured with the OpenCensus receiver, using mTLS (mutual TLS)?

My poc works when the `ocagent` is set to insecure, as the collector logs the traces.

However when TLS credentials are set on both sides, the `ocagent` seems to hang on connecting and the collector shows 0 traces.

The same TLS files are valid because they worked with an OT instrumented app and the collector configured with the OT receiver using mTLS.

I feel like I'm missing a piece here and hope to find someone who's been able to confirm or deny if there's a problem with `ocagent` or the collector?
