### ISSUE TITLE
[hostmetrics] Mismatch with OpenTelemetry specification

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#2220]
**Describe the bug**

The OpenTelemetry specification defines a series of [semantic conventions for system metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/semantic_conventions/system-metrics.md#semantic-conventions-for-system-metrics), some of which are sent by the hostmetrics receiver. However, there is some mismatch in naming between the spec metrics and the ones sent by this component.

For example, the swap metrics are under the `system.swap` namespace in the hostmetrics receiver:

https://github.com/open-telemetry/opentelemetry-collector/blob/618095055f4514cbf3066b39ac63281e2f95de9d/receiver/hostmetricsreceiver/internal/scraper/swapscraper/swap_metadata.go#L55-L56

while the equivalent metric in the specification is [under the `system.paging` namespace](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/semantic_conventions/system-metrics.md#systempaging---pagingswap-metrics).

Some other metrics have different names under the same namespace (`system.network.dropped` v. `system.network.dropped_packets`), are missing from the spec (`system.cpu.load_average` metrics) or are missing in the receiver (`system.cpu.utilization`, maybe covered by the `load_average` metric?)

**Steps to reproduce**
Run the hostmetrics receiver

**What did you expect to see?**

Metrics matching the specification semantic conventions

**What did you see instead?**

Metrics with different naming to the one defined in the specification.

**What version did you use?**
Latest commit: b19b5ac392ec6a630b7dae6c90f7354c77b897f3

**What config did you use?**
Config: N/A

**Comment by mx-psi** [comment]
cc @james-bebbington, and cc @bogdandrutu since you made some changes related to this.

I am not sure if this is a misunderstanding on my part or if it is a bug but I believe there could be another issue, this one related with the types used for the reported metrics, and I wanted to clarify things.

For example, the `system.filesystem.usage` metric reports the number of used bytes through `gopsutil` (calling [`disk.Usage`](https://godoc.org/github.com/shirou/gopsutil/disk#UsageStat)). This is set as a cumulative `IntSum`:

https://github.com/open-telemetry/opentelemetry-collector/blob/65588cc97912989f533e647a6caba5e99c50e1fe/receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_metadata.go#L41-L51

but my impression is that this does not match the description of `IntSum`s or cumulative metrics [from the protobuf](https://github.com/open-telemetry/opentelemetry-proto/blob/d0e9c0c92e9defe96251be18ce82991e6ec30b54/opentelemetry/proto/metrics/v1/metrics.proto#L175-L182):

> Sum represents the type of a numeric int scalar metric that is calculated as a sum of all reported measurements over a time interval.

and

> aggregation_temporality describes if the aggregator reports delta changes since last report time, or cumulative changes since a fixed start time.

I don't think the number of bytes used can be interpreted either as a "sum of all reported measurements over a time interval" nor as reporting "cumulative changes since a fixed start time" (to me it looks like a gauge). A similar argument can be made for all other metrics reported by this component that are not monotonic.

Are these types correct? What is the justification for using `IntSum` as a type and setting the aggregation temporality as cumulative?

**Comment by james-bebbington** [comment]
> Some other metrics have different names under the same namespace (`system.network.dropped` v. `system.network.dropped_packets`), are missing from the spec (`system.cpu.load_average` metrics) or are missing in the receiver (`system.cpu.utilization`, maybe covered by the `load_average` metric?)

Thanks for creating this bug. Yes there are a few cases of mismatched naming because the host metrics receiver predates the spec. We need to update some of the metric names / types. If I have some time, I will try to get to this shortly.

Note there may be some metrics captured by the host metrics that aren't defined in the spec (e.g. the `load_average` metrics you mentioned) which I think is fine to leave as is. Likewise, there may be things defined in the spec that we don't measure here. It was intentional to not measure `system.cpu.utilization` in this receiver since that is a metric that can be directly derived from `system.cpu.usage`.

> I don't think the number of bytes used can be interpreted either as a "sum of all reported measurements over a time interval" nor as reporting "cumulative changes since a fixed start time" (to me it looks like a gauge). A similar argument can be made for all other metrics reported by this component that are not monotonic.

I agree this is quite confusing, and probably the proto definition could be a bit clearer. My understanding is that you can think of filesystem usage as a series of writes (sometimes deletes) to disk that either increase or decrease the total disk usage. In that sense, this metric represents a cumulative change since a fixed start time (when the machine booted up). The fact that we actually measure disk usage asynchronously via a system function that directly gives us the total value at a point in time doesn't matter; it's how the underlying values are calculated that matters.

One important thing to note about `IntSum` metrics is that the rate always has some meaning, here it represents the change is disk usage. In cases where you use a gauge to represent a metric, that will not necessarily be the case.

**Comment by mx-psi** [comment]
Thanks for the detailed answer!

> Thanks for creating this bug. Yes there are a few cases of mismatched naming because the host metrics receiver predates the spec. We need to update some of the metric names / types. If I have some time, I will try to get to this shortly.

Awesome, thank you.

> My understanding is that you can think of filesystem usage as a series of writes (sometimes deletes) to disk that either increase or decrease the total disk usage. In that sense, this metric represents a cumulative change since a fixed start time (when the machine booted up). 

I see how that can make sense; I agree with you that it would be beneficial to update the protobuf description to avoid this kind of confusion, I might look into proposing some rephrasing for this in the future.

**Comment by james-bebbington** [comment]
I think this is okay to close now. Feel free to re-open if you still think there's more work to be done @mx-psi

**Comment by mx-psi** [comment]
Awesome, the changes make sense to me, thanks for taking care of it!
