### ISSUE TITLE
Fix the inaccurate mention of headers in prometheusremotewriteexporter

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector#2268]
The headers setting allow users to pass any headers in the outgoing requests:

- `headers`: additional headers attached to each HTTP request. If
  `X-Prometheus-Remote-Write-Version` is set, its value must be `0.1.0`

X-Prometheus-Remote-Write-Version is called out here if users want to send this header but we override it in the exporter:

```
httpReq.Header.Add("Content-Encoding", "snappy")
httpReq.Header.Set("Content-Type", "application/x-protobuf")
httpReq.Header.Set("X-Prometheus-Remote-Write-Version", "0.1.0")
httpReq.Header.Set("User-Agent", "OpenTelemetry-Collector/"+version.Version)
```

We should fix the document not to give an impression these headers can be specified by the user.

cc @huyan0 @amanbrar1999 @JasonXZLiu

**Comment by amanbrar1999** [comment]
I believe it actually works the other way around. the "headers" section comes from the `confighttp` module, and these headers overwrite everything because they get added from an interceptor. https://github.com/open-telemetry/opentelemetry-collector/blob/master/config/confighttp/confighttp.go#L46

The headers specified in the exporter code are added before the request, then when the request is made the interceptor will overwrite these headers. Perhaps a separate concern in this case is that users have the ability to overwrite these headers that are required for successful communication?

**Comment by amanbrar1999** [comment]
I believe Jason's PR https://github.com/open-telemetry/opentelemetry-collector/pull/2269 resolves this issue

**Comment by rakyll** [comment]
#2269 solves this, closing.
