### ISSUE TITLE
Simplify memorylimiter config

### ISSUE THREAD

**Issue by markfink-splunk** [open-telemetry/opentelemetry-collector#2516]
Set the memorylimiter in config.yaml and be done with it.  Why also have the command line argument?  It complicates things unnecessarily to always have to set it in 2 places (command line argument + config.yaml), particularly when they always must be set the same anyway (at least per the README for the memorylimiter).  If there was a use-case where they could/should be set differently, or if say the command-line overrides config.yaml but is otherwise not required, then it would make sense.

**Comment by markfink-splunk** [comment]
Better yet, if best practice is to always set the memory limiter and in general, it should always be set to 1/3 of system memory, and then the limit percentage should (generally) always be 90%, and spike limit should always be 25%, then why not make all that the default?  So that the user does not need to even know about it, unless they have a good reason to change it.

**Comment by gramidt** [comment]
This makes sense, @markfink-splunk. Are you planning on creating a PR? If not, I will help address this.

**Comment by markfink-splunk** [comment]
I won't have time to work on this myself for awhile, probably a month or so. Granted, it's not a burning issue.  I just had the thought and wanted to submit it before I forgot about it.  I believe it will help adoption.

**Comment by flands** [comment]
@pjanotti I believe there was a reason why this was required -- do you recall?

**Comment by bogdandrutu** [comment]
@mxiamxia there are few issues here:
1. There is the "memory ballast" problem that right now is an internal thing in the Service, (I made a PR to add an extension but did not finish the work to enable and deprecate the flag for that). Right now users have to configure ballast in 2 places if I am not wrong.
2. It would be good to have a way to configure percentage of memory allocated to a POD for example instead of absolute values. 

@flands please bring more details from user feedback

**Comment by mxiamxia** [comment]
Thanks @bogdandrutu . 

Dug into the current ballast settings. Before the new ballast extension was added,  the command line `--mem-ballast-size-mib` was the only place where truly enables `ballast` mem allocation. `mem_limiter` processor doesn't do `ballast` memory allocation but just to make sure the collector only consume certain memory under the limit. (drop data & force GC)

It's not a good idea to enable `ballast` with memory allocation in `memory_limiter` processor because it is pipeline level component. So we have to have two `ballast` settings but for different purpose. I am fine to move `ballast` memory allocation to a new extension.

What I'll do,
1. Add the new config `size_mib_in_percentage` in `ballastextension`. The total available memory will be determined by `cgruops` and it is only supported in linux. 
2. I'll remove `--mem-ballast-size-mib` and related code.

>configure percentage of memory allocated to a POD for example

@bogdandrutu , do you refer to k8s pod?

**Comment by mxiamxia** [comment]
To support the percentage configuration based on total available memory for docker and containers running in k8s pod. The proposed design will be looked like, 
1. Identify the memory limit cgroup path location by looking up `/proc/self/cgroup` and `/proc/self/mountinfo`. 
2. Once the cgroup memory file path identified, check the value in `memory.limit_in_bytes` under the identified path (eg `/sys/fs/cgroup/memory/memory.limit_in_bytes`). if the output bytes value is `9223372036854771712`(`0x7FFFFFFFFFFFF000`) which indicates the container or AOC running on the pyshical host doesn't have memory limit set in cgroup. 
           2.1.  For the collector running in the containers/k8s (containerd, docker). The collector will return `err` during the ballast extension startup.
          2.2.  For the psychical hosts, it will get the total memory in step 3 below
3. For physical host, will get total available memory from `/proc/meminfo` (see `sed -n -e '/^MemTotal/s/^[^0-9]*//p' /proc/meminfo`) if there is no cgroup limit found for the running collector.
cc @alolita , @bogdandrutu

**Comment by alolita** [comment]
Ping @mxiamxia ? what is the status on this issue?

**Comment by mxiamxia** [comment]
Hi @alolita, I am going to send a new PR to deprecate the old ballast memory creation implementation.

**Comment by mxiamxia** [comment]
The issue can be closed.

cc/ @alolita @bogdandrutu
