### ISSUE TITLE
[Document/Agree on] all packages/modules that will be marked as stable during first stability phase.

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2544]
Phase 1 list of packages to mark stable:

- [ ] - component (only traces)
- [ ] - component/componenterror
- [ ] - component/componenthelper
- [ ] - component/componenttest
- [ ] - config
- [ ] - config/configmodels
- [ ] - consumer (only traces)
- [ ] - consumer/consumererror
- [ ] - consumer/consumertest
- [ ] - consumer/pdata (only traces)
- [ ] - obsreport 
- [ ] - obsreport/obsreporttest
- [ ] - service
- [ ] - service/defaultcomponents

**Comment by tigrannajaryan** [comment]
@bogdandrutu FYI, I updated the list.

**Comment by bogdandrutu** [comment]
@tigrannajaryan thanks. For the config, can we aim only for config and configmodels and not the others?

**Comment by bogdandrutu** [comment]
@tigrannajaryan and @bogdandrutu updated the list of components we will focus on in the Phase 1. @alolita @jpkrohling can you take a look as well?

**Comment by jpkrohling** [comment]
Not sure I see why `obsreport` should be in phase 1. Does it mean it's going to be changed to use OpenTelemetry instead of OpenCensus before the phase 1 is completed? Funcs like the one below wouldn't be needed after this migration, from what I understand:

https://github.com/open-telemetry/opentelemetry-collector/blob/892fe4febba181239b6bd0a66323c423f66a0558/obsreport/obsreport.go#L87

How about the specific component helpers, like the exporterhelper?

**Comment by bogdandrutu** [comment]
@jpkrohling up for this, I will remove from phase 1 and move all issues to phase 2.

**Comment by bogdandrutu** [comment]
Closing this issue and open tracking issue for all of these.
