### ISSUE TITLE
 Investigate tools that check for API compatibility for go modules

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2545]
Enable them for modules that we mark as stable.

**Comment by seankhliao** [comment]
As part of golang/go#26420 the Go team is experimenting with [gorelease](https://pkg.go.dev/golang.org/x/exp/cmd/gorelease) and the related [apidiff](https://pkg.go.dev/golang.org/x/exp/cmd/apidiff)

**Comment by Aneurysm9** [comment]
We have a need for similar capability in the Go SDK, so I can take this on.

**Comment by Aneurysm9** [comment]
I was able to use `apidiff` to generate an API snapshot from the `v0.23.0` release and then compare against the current HEAD and it appears to correctly identify changes:

```console
$ make apidiff-compare                                                     
Changes found in go.opentelemetry.io/collector/consumer/consumererror:
Incompatible changes:
- CombineErrors: removed
- PartialError: removed
- PartialLogsError: removed
- PartialMetricsError: removed
- PartialTracesError: removed
Compatible changes:
- AsLogs: added
- AsMetrics: added
- AsTraces: added
- Combine: added
- Logs: added
- Metrics: added
- NewLogs: added
- NewMetrics: added
- NewTraces: added
- Traces: added
Changes found in go.opentelemetry.io/collector/consumer/pdata:
Incompatible changes:
- DoubleSummary: removed
- DoubleSummaryDataPoint: removed
- DoubleSummaryDataPointSlice: removed
- Metric.DoubleSummary: removed
- MetricDataTypeDoubleSummary: removed
- NewDoubleSummary: removed
- NewDoubleSummaryDataPoint: removed
- NewDoubleSummaryDataPointSlice: removed
Compatible changes:
- Metric.Summary: added
- MetricDataTypeSummary: added
- NewSummary: added
- NewSummaryDataPoint: added
- NewSummaryDataPointSlice: added
- Summary: added
- SummaryDataPoint: added
- SummaryDataPointSlice: added
Changes found in go.opentelemetry.io/collector/exporter/exporterhelper:
Incompatible changes:
- CreateTraceExporter: removed
Compatible changes:
- CreateTracesExporter: added
Changes found in go.opentelemetry.io/collector/obsreport:
Incompatible changes:
- NewExporter: changed from func(go.opentelemetry.io/collector/config/configtelemetry.Level, string) *Exporter to func(ExporterSettings) *Exporter
Compatible changes:
- ExporterSettings: added
```

This is currently operating on all packages in the `go.opentelemetry.io/collector` module.  `apidiff` appears to not allow specifying a package version at runtime and must be in the directory containing `go.mod` for the package's module when generating a snapshot of the package API in order to use the files on disk, so additional work will be required to support scanning multiple modules.

```console
$ apidiff go.opentelemetry.io/collector/exporter/exporterhelper@v0.23.0 go.opentelemetry.io/collector/exporter/exporterhelper
loading go.opentelemetry.io/collector/exporter/exporterhelper@v0.23.0: -: can only use path@version syntax with 'go get' and 'go install' in module-aware mode
```

@bogdandrutu do you want my to put up a PR with things as I have it now, or should I continue working on being able to operate on a per-module basis?  Chances are I wouldn't be able to pick up that work again until next week.

**Comment by alolita** [comment]
@Aneurysm9 can you create an issue for building a GitHub Action workflow to check when changes are added (its an API diff check in a GHA workflow)?

cc @mxiamxia

**Comment by bogdandrutu** [comment]
Probably we should have a github action that compares the PR with head and adds a comment or fails if changes are identified

**Comment by alolita** [comment]
Closing this issue as discussed with @bogdandrutu 

New issue is https://github.com/open-telemetry/opentelemetry-collector/issues/3220
