### ISSUE TITLE
TestDefaultComponents does not pass on github actions

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2738]
```
=== RUN   TestDefaultComponents
    defaults_test.go:136: 
        	Error Trace:	defaults_test.go:136
        	            				defaults_test.go:83
        	Error:      	Received unexpected error:
        	            	listen tcp 127.0.0.1:1777: bind: address already in use
        	Test:       	TestDefaultComponents
--- FAIL: TestDefaultComponents (0.00s)
```

**Comment by pjanotti** [comment]
This happened at the `Start` of the first instance of `pprofextension` with the default config. Because of the port in question, this may be due to the same extension having "leaked" from another test. That said this test can be more resilient to ports not available by using the test helper - I will open a PR for it.
