### ISSUE TITLE
Ensure consistent pattern with functions referencing multiple signals

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-collector#2759]
> I like the analogy with generics/templates. Maybe we can document this in contribution.md. There are some places where we did not follow this rule like `consumertest.TracesNop`. Maybe file in issue to follow this pattern everywhere :)

_Originally posted by @bogdandrutu in https://github.com/open-telemetry/opentelemetry-collector/pull/2742#discussion_r599005930_

Review the codebase and ensure a consistent pattern is used with functions/initializers that have multiple variants to handle multiple signal types.  We should consistently have the signal identifier at the end of the name, such as `PartialTraces` and `PartialMetrics` and not `TracesPartial` or `MetricsPartial`.  This will ensure that related functions sort together in documentation and allow developers working with the code to expect consistency which can reduce cognitive load.

Update the contribution guidelines to reflect this preference.

**Comment by bogdandrutu** [comment]
It may be a bit too late for this change, we should look into it because this pattern is used for `consumer.TracesConsumer` as well as for `component.TracesExporter`.

The consumer can be probably rename to `consumer.Traces` and the component to `component.ExporterTraces` but we need to be confident that this is what we want. I actually like `consumer.Traces`

**Comment by alolita** [comment]
@bogdandrutu should this issue be closed? was the rename to consumer.traces done @Aneurysm9 ?

**Comment by atoulme** [comment]
Closing as completed. Reopen if more work is needed.
