### ISSUE TITLE
Maintain trace Id's length

### ISSUE THREAD

**Issue by ignasi35** [open-telemetry/opentelemetry-collector#3072]
**Is your feature request related to a problem? Please describe.**

The translator for Jaeger TraceId's expands 64bit traceId's to 128bit.

Using those traceId's on legacy backend's is not possible. For example, AWS's XRay limits the traceId length to 64bit.

We've observed that conversion on the following setup:

```
 [ user-app -(1)-> otel-side-car ] -(2)-> aws-otel-collector -(3)-> Cloudwatch/XRay
```

where

- `user-app` is some user code producing 64bit traceIds using the Jaeger Java client library.
- `(1)` is Thrift's jaeger protocol
- `otel-side-car` is the vanilla https://github.com/open-telemetry/opentelemetry-collector/ v0.25.0
- `(2)` is OTLP-gRPC traces 
- `aws-otel-collector` is the https://github.com/aws-observability/aws-otel-collector v0.9.0

It'd be good if the traceIds in the OTLP representation in `(2)` were still 62bit in length.

**Describe the solution you'd like**

It'd be good to maintain the id's exactly as received throughout the conversion.

**Comment by bogdandrutu** [comment]
/cc @anuraaga 

> For example, AWS's XRay limits the traceId length to 64bit.

I think the traceID is 128 but has a special representation.

**Comment by rakyll** [comment]
X-Ray trace ID is 64 bit but we are working on to make it 128 bit.

**Comment by anuraaga** [comment]
To clarify, AWS uses 128-bit trace IDs but the first 32 buts must be a timestamp, not random. There is ongoing work to lift this restriction at some point, and then the collector will work fine without changing if generation.

I think in general having 128-bit in the collector is fine even for 64-bit IDs - most exporters can deal with zero padding, or otherwise strip it. X-Ray is unique in not having any way to deal with it and we're working on the backend to fix it. I don't think there's any work to do in the collector though.

**Comment by rakyll** [comment]
We can close this and track it via https://github.com/aws-observability/aws-otel-collector/issues/492. It's not a collector issue.

**Comment by bogdandrutu** [comment]
Thanks @rakyll
