### ISSUE TITLE
Remove `testutil.LimitedWriter`

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3225]
1. Implement an always return error io.Writer and use it in the fileexporter tests.
2. Copy the current code in contrib/receiver/fluentforwardreceiver to be used there in tests. Ensure not publish, move to a _test file.

/cc @alolita for triage

**Comment by sethAmazon** [comment]
I would like to take up this issue.

**Comment by sethAmazon** [comment]
I have a few questions about this ticket. 
1. "Implement an always return error io.Writer" does this mean always return error when the writer is called? This will cause current test cases to fail. 
2. Is there a better way than just copying "current code in contrib/receiver/fluentforwardreceiver" this seems bad since there would be no way to keep the copied code up to date with the contrib repo. 
3. I'm assuming when the new io.Writter is implemented. That will replace testutil.LimitedWriter in the fileexporter test cases. 
4. contrib/receiver/fluentforwardreceiver code with be used in another pr? I do not see in the issue how this going to be used in the tests.

**Comment by bogdandrutu** [comment]
> "Implement an always return error io.Writer" does this mean always return error when the writer is called? This will cause current test cases to fail.

Which test cases?

> Is there a better way than just copying "current code in contrib/receiver/fluentforwardreceiver" this seems bad since there would be no way to keep the copied code up to date with the contrib repo.

We copy the code there and delete from here, so only one copy of the code.

> I'm assuming when the new io.Writter is implemented. That will replace testutil.LimitedWriter in the fileexporter test cases.

Yes

> contrib/receiver/fluentforwardreceiver code with be used in another pr? I do not see in the issue how this going to be used in the tests.

You should start with a PR in fluentforwardreceiver first.

**Comment by sethAmazon** [comment]
I made a mistake when testing creating an allows error writer does not cause tests to start failing.

**Comment by sethAmazon** [comment]
Hi @bogdandrutu  I'm still not understanding the context of fluentforwardreceiver code change. 
I can't find the directory structure of contrib/receiver/fluentforwardreceiver
I did find the directory receiver/fluentforwardreceiver in the opentelemetry-collector-contrib
I'm assuming I need to copy that directory into repo opentelemetry-collector directory receiver/fluentforwardreceiver
Then make all the go files have _test. 
I'm not sure what to do with other files like readme in this directory. 
Is what I'm saying correct or am I missing something. 

I'm going to split this ticket into multiple pr and send out a pr for the always error log writer today.
