### ISSUE TITLE
Pipeline requirements for data immutability

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#368]
Currently it is not very well documented if a processor or exporter is allowed to change the received Metrics/Trace Data or a copy is required.

I would propose to document this, probably a safe assumption is to say that every object in the Metrics/Trace Data is considered immutable.

Some examples:

Changing the name of a metric see https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/metrics/v1/metrics.proto#L37), I should be able to reuse all the sub-parts of the Metric that I do not touch:
```golang
func rename(m *metricspb.Metric) *metricspb.Metric {
return &metricspb.Metric{
  MetricDescriptor: &metricspb.MetricDescripor {
    Name: "prefix" + m.MetricDescriptor.getName();
    Description: m.MetricDescriptor.getDescription();
    ...
  }
  TimeSeries: m.TimeSeries,
  ...
}
}
```
So the objects that I changed I had to create new once, but for things that are not-changed I used the same received objects.

Adding/Removing/Changing a new metric in the MetricsData (the slice of metrics is considered immutable so I cannot change that):
```golang
func renameAll(md *consumerdata.MetricsData) *consumerdata.MetricsData {
  ms := make([]*metricspb.Metric, 0, len(md.Metrics)
  for _, m := range md.Metrics {
    ms = append(ms, rename(m))
  }
  return &consumerdata.MetricsData {
    Node: md.Node,
    Resource: md.Resource,
    Metrics: ms,
  }
}
```

This are just some examples to clarify that we should document that all the objects are considered immutable and we should not allow a processor/exporter to change anything in the received data.

**Comment by tigrannajaryan** [comment]
This is a good point and is related to https://github.com/open-telemetry/opentelemetry-service/issues/353

The proposed approach with immutable objects is similar to the copy-on-write approach.

The other approach is cloning objects instead of sharing them and letting processors modify them instead of placing immutability requirements.

This is a tradeoff that does not have an obvious choice.

If we choose immutability we will have faster and more memory efficient operation in case of multiple pipelines that don't modify the data. However the downside is that it may be quite slow if we need the processors to modify the data (for example if we have multiple processors in a pipeline and they all modify data). This also complicates implementation. The proposed approach to reuse unchanged sub-parts and replace changed parts is basically copy-on-write, and every piece of code that makes a modification must do this correctly. We go's lack of ability to actually declare objects immutable there is no way to enforce this.

If we choose to clone the data instead of sharing we will have faster operation in case of one pipeline and processors that modify the data. It is also much simpler from implementation perspective (here is the PR that implements it: https://github.com/open-telemetry/opentelemetry-service/issues/353)

**Comment by bogdandrutu** [comment]
Happy with any option you propose (and maybe test a bit), but want to clearly state the requirements :)

**Comment by bogdandrutu** [comment]
I think indeed my proposal is a kind of copy-on-write with some knowledge about the structure of the data (we do not clone the entire object).

Maybe we can have a "service" config and all the processors that require to change the data will have access to?

**Comment by tigrannajaryan** [comment]
Done via https://github.com/open-telemetry/opentelemetry-collector/pull/378
