### ISSUE TITLE
Stringify non-string attributes for exporters requiring strings

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#3815]
This issue addresses `TODO: Decide what to do with non-string attributes.` comments in the code. 

As per @tigrannajaryan's comment in this discussion https://github.com/open-telemetry/opentelemetry-collector/pull/3770#discussion_r685681885

>We should probably stringify non-string attributes. Unclear what encoding to use though for non-primitive types. Perhaps json-string or something like that since that's also what Otel spec recommends for exporting array attributes when arrays are not natively supported in the target format: https://github.com/open-telemetry/opentelemetry-specification/blob/7cef355a15c4430aa323d155206a2945fcd67a05/specification/common/common.md#attributes

- [x] https://github.com/open-telemetry/opentelemetry-collector/pull/3770/files#diff-9822bc07132ceeeb9c69a90898caccf2d9f9acefe0cef5b5bae0dc2cc9e44764R265 #3821
- [x] https://github.com/open-telemetry/opentelemetry-collector/pull/3770/files#diff-59096f8af265799d33e8452f5323b2928279fb46ae2765c62261deb7fcd12182R87 #3821
- [x] https://github.com/open-telemetry/opentelemetry-collector/pull/3770/files#diff-b1bd694f5f323e20628c2b86a8cff274452d1b5844ce3b0384234f10783d79bfR138 #3821
- [x] https://github.com/open-telemetry/opentelemetry-collector/pull/3770/files#diff-53ed36b4ffe6625d3c10c4660f745d81914dbd5466869353a3ae00299c4852b7R422 #3821
- [ ] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4589/files/c887e318af4bc4a26286055c78451008862da95b#diff-c67f9c92b1265c0902af61f14485079fb55d3282838c5a212d743000c78d39b1R40
- [ ] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4590/files#diff-a1345639d3f87593482f9ead95926bf99da46ef8c850a065f577422f05bf90b9R97
- [ ] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4588/files#diff-c5ee095183be0a559532bb7a97264bd49d11f959a0ba60ccdf2b763ea357e377R177
- [ ] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4588/files#diff-c5ee095183be0a559532bb7a97264bd49d11f959a0ba60ccdf2b763ea357e377R208
- [ ] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4599/files#diff-062692229596ad1bc5eb7ce94a108aef9188ab729b0999f5b12b90eba3f60391R62
- [ ] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4601/files#diff-e24ea81aae9305a81a212e6e6d4aab9897717b84156ae2bfaf5e623206623e63R110
- [ ] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4603/files#diff-d328fdc36e4df3c9aaf8e9425205a130f10e49dba18d8d1715326f0f0001f134R147
- [ ] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4613/files#diff-f3775c0b5864c2dca492932308d1bea71760031919a7c877e62d0c528f1c3f5dR233
- [ ] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4614/files/9e236103ae50b54529df8a59c1611e18bb95c313#diff-7ab9fa22126292a4cb18c74ec6309729f3fc05049b7e5889dd80266db71f8f43R204
- [ ] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4614/files/9e236103ae50b54529df8a59c1611e18bb95c313#diff-1399f721999dc4a34ae0dd2b665737a96f9dcc4d188febbadb82849e9e8e11e5R425

**Comment by codeboten** [comment]
See the following code:

https://github.com/open-telemetry/opentelemetry-collector/pull/3770/files#diff-9822bc07132ceeeb9c69a90898caccf2d9f9acefe0cef5b5bae0dc2cc9e44764R265

https://github.com/open-telemetry/opentelemetry-collector/pull/3770/files#diff-59096f8af265799d33e8452f5323b2928279fb46ae2765c62261deb7fcd12182R87

https://github.com/open-telemetry/opentelemetry-collector/pull/3770/files#diff-b1bd694f5f323e20628c2b86a8cff274452d1b5844ce3b0384234f10783d79bfR138

**Comment by tigrannajaryan** [comment]
I would suggest to convert primitive values to human-readable strings. So for example:
1. Integer 5 becomes a string `5`.
2. String "abc" remains a string `abc` (Note that the string is NOT surrounded by additional double quotes).
3. Boolean true becomes a string `true`.
4. Double 1.5 becomes a string `1.5`.
5. String “1.5” remains a string `1.5` (and is indistinguishable from a double 1.5).

For arrays and KV lists we perform JSON-like marshalling. So, for example:
1. An array of 3 integers (1,2,3) becomes a string `[1,2,3]`.
2. An array of 2 strings ("abc", "def") becomes a string `[abc, def]` (note that the array elements are NOT surrounded by double quotes).
3. Key value list with 2 pairs ("abc"->123, "foo"->"bar") becomes `{"abc":123, "foo":bar}`.

For bytes values we use base64 encoding. For example:
A sequence of 5 bytes in hex notation (00 01 02 03 04 05) becomes a string `AAECAwQF` (note that the string is NOT surrounded by additional double quotes).

The conversion is obviously non-reversible and it is impossible to write a parser that converts it back correctly. We intentionally sacrifice it in order to have a very straightforward representation of string attributes, which is the most important use case.

We can play with a variation of these rules for a bit better outcome but ultimately it will remain non-reversible unless we make the primary use case (the plain string attribute) straightforward.

We should probably also make these definitions part of the Otel spec.

**Comment by tigrannajaryan** [comment]
> We already have an `AttributeValue` to `string` function that is used for the `resource_to_telemetry_conversion` setting of the `exporterhelper`. This could be used as a starting point

Good point.

**Comment by codeboten** [comment]
@mx-psi @tigrannajaryan would the best way to solve this then to move `AttributeValueToString` from `tracetranslator` to `pdata` to make it less trace specific?

**Comment by mx-psi** [comment]
That makes sense to me, but I would agree with @tigrannajaryan that this should probably be part of the spec

**Comment by tigrannajaryan** [comment]
> @mx-psi @tigrannajaryan would the best way to solve this then to move `AttributeValueToString` from `tracetranslator` to `pdata` to make it less trace specific?

Yes, sounds good to me, especially if this behavior is defined in the spec.


> That makes sense to me, but I would agree with @tigrannajaryan that this should probably be part of the spec

We should "legalize" our implementation by submitting a PR against spec repo. Can be done in parallel or after this change.
