### ISSUE TITLE
Restore healthcheckextension to the core collector

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-collector#3945]
**Is your feature request related to a problem? Please describe.**

The healthcheckextension was moved from core to contrib. Because of this, it becomes very difficult to deploy the core collector in a container environment like k8s. Even just testcontainers in the Java integration tests were extremely flaky until we ensured the tests run after the healthcheck passes.

I suspect many that are deploying collector in production will have to switch to collector-contrib. I don't believe this is the intention of the stability milestone in the roadmap.

Note that healthcheckextension was planned to stay in core

https://github.com/open-telemetry/opentelemetry-collector/issues/3474#issuecomment-870946670

So I suspect the removal may have missed some needed discussion.

**Describe the solution you'd like**

Restore the healthcheckextension. If the current implementation is too heavyweight because of a jaeger dependency, just returning HTTP 200 on a well known port would be enough.

**Describe alternatives you've considered**

If another endpoint has a URL that always returns an HTTP 200, it could potentially be used but awkward.

**Additional context**

_Please delete paragraphs that you did not use before submitting._

**Comment by anuraaga** [comment]
By the way, I heard that the published docker image will have the healthcheckextension - if so I think the priority isn't as high. While healthchecks are still used outside, they are vastly more common and necessary in container deployments so they would be covered.

**Comment by alolita** [comment]
Good callout @anuraaga The healthcheckextension is planned to be used for core. There is also a proposal to enhance the current implementation.

**Comment by ymotongpoo** [comment]
Thank you for calling this out, @anuraaga, and thank you for the triage, @alolita. My view is even more aggressive, I think healthz should be included as default extension that runs without any configurations and just works as healthcheck endpoint, like:

```
func healthz(w http.ResponseWriter, r *http.Request) {
  w.Write([]byte("OK"))
}
```

and no other heavy duty works in it.

@alolita, could you share the status of the proposal you mentioned in your comment (https://github.com/open-telemetry/opentelemetry-collector/issues/3945#issuecomment-911277542)? Because OTel Trace is now stable in the collector, having production ready feature by default should be reasonable.

**Comment by TylerHelmuth** [comment]
We just ran into this need as well in our OpenShift deployment.  Would love the core distribution to support returning a 200 at /healthz

**Comment by atoulme** [comment]
It's there: https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol/manifest.yaml#L33

Closing as completed.
