### ISSUE TITLE
How to handle duplicate names in semantic conventions?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#4000]
Right now all our semantic conventions (resource attributes, span attribute, span event attributes, span event names, etc.) are in one package which is convenient, but may cause issues when more semantic conventions will be added for logs, metrics, etc.

Questions:
* Do we need to worry about this?
* How do we plan to handle this in case of conflicts? Would these conflicts be expected and we are going to "reuse" same values?

There is a need to clarify this, and clarify the naming structure for our semantic conventions.

**Comment by tigrannajaryan** [comment]
Just chatted offline with @bogdandrutu and I think the best/simplest initial approach is the following:
- Prohibit attributes with the same name and different semantics for different signals.
- It is fine to have an attribute with the same name and semantics for different signals. For example "http.method" can be recorded as a span attribute or as a metric attribute and it is completely fine since it has the same semantics and the same set of possible values.

If in the future we discover that there is a need to have attributes with the same name but different semantics for different signals we can change this rule. We will need to introduce some sort of namespacing in the semantic convention generator to use the namespaces in the generated symbol names.
