### ISSUE TITLE
Add test for DefaultHTTPInterceptor

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#4555]
For some reason, a test for `configauth.DefaultHTTPInterceptor` is currently missing. There should definitely be a test for it.

**Comment by jpkrohling** [comment]
This code has been moved to this place:
https://github.com/open-telemetry/opentelemetry-collector/blob/84b37067b2b3d678278556156e1e1db4fc595378/config/confighttp/confighttp.go#L317-L327

**Comment by joseph-woodward-form3** [comment]
I'm happy to pick this one up?

**Comment by JosephWoodward** [comment]
I'm happy to pick this one up?

**Comment by jpkrohling** [comment]
It is yours!

**Comment by jpkrohling** [comment]
@JosephWoodward, do you need help moving forward with this?

**Comment by JosephWoodward** [comment]
@jpkrohling I had a quick look, but didn't get as much time over Christmas as I was hoping to. Now everything is settling down again I can get it sorted.

Whilst looking at it I noticed the [TestServerAuth](https://github.com/open-telemetry/opentelemetry-collector/blob/e6f0e014c0ad280fc67557704a2015924caf76eb/config/confighttp/confighttp_test.go#L770) test covers the happy path of that default handler, so I presume this issue is to cover if an error is returned, is that correct?

**Comment by jpkrohling** [comment]
>so I my understanding is this issue is to cover if authenticate returns an error, is that correct?

Yes, that seems right. Looks like the happy path is covered.

**Comment by JosephWoodward** [comment]
@jpkrohling Great, I've raised a PR [here](https://github.com/open-telemetry/opentelemetry-collector/pull/4647)

**Comment by JosephWoodward** [comment]
This issue can now be closed :+1:

**Comment by bogdandrutu** [comment]
Thanks @JosephWoodward
