### ISSUE TITLE
[pdata] Consider renaming of MetricValueType

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#4819]
`MetricValueType` type sounds confusing. It's not a type of any metric value, it's applicable to numeric values only.

Originally raised by @bogdandrutu https://github.com/open-telemetry/opentelemetry-collector/pull/4811#discussion_r801186353:

> On the list of "may fix": MetricValueType does not sound as the best name for the enum. Maybe NumberValueType? PointValueType? Not sure, just open an issue, this name does not sound very clear to me, because I would ask why Histogram is not a value type.

**Comment by Aneurysm9** [comment]
I think it is going to get confusing if there is any more than this and https://github.com/open-telemetry/opentelemetry-collector/issues/4818.  If we're going to consider renaming a number of types or methods or fields in the pdata package we should have a single overarching issue and a design doc for it so that we can consider the change holistically.

**Comment by dmitryax** [comment]
These issues are created as soon they discovered. At this point I don't plan to create any new. I believe discussing each of these renames under dedicated issues is more convenient than putting them together as they are pretty much independent. If other @open-telemetry/collector-approvers think it's worth an overarching issue and a doc, I can do it.
