### ISSUE TITLE
Access to Collector Log Pointer is not atomic

### ISSUE THREAD

**Issue by cpheps** [open-telemetry/opentelemetry-collector#4939]
**Describe the bug**
Access to the collectors [log pointer](https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/collector.go#L95) is not atomic. If `GetLogger` is called before `Run` the returned pointer is no longer valid as it is updated during [startup](https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/collector.go#L177). 

It also presents a race condition between calling shutdown and run as shutdown could reference the pointer in the [recover](https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/collector.go#L118) before or after it's set.

**Steps to reproduce**
1. Call `GetLogger` before `Run`
2. Call `Run`
3. Observe GetLogger is still using the noop logger

**What did you expect to see?**
If I call `GetLogger` before `Run` the pointer I'm given should update and log.

**What did you see instead?**
Log pointer is not atomic so `GetLogger` will return a different point before and after `Run` is called.

**What version did you use?**
v0.45.0

**What config did you use?**
Any will work

**Environment**
OS: MacOS 12.2.1
Compiler(if manually compiled): go 1.17.6

**Additional Context**

Action item from #4827

**Comment by cpheps** [comment]
@patil-kshitij by all means. I might have capacity to do so until next week so feel free.

**Comment by dmitryax** [comment]
cc @djaglowski

**Comment by sakshi1215** [comment]
Hey @dmitryax @cpheps Can you please assign this issue to me, I would like to take a dig at this.

**Comment by dmitryax** [comment]
Thanks @sakshi1215. Assignd

**Comment by sakshi1215** [comment]
I was looking at this issue & have noticed that its no longer valid. Since version 0.54 we have remove the GetLogger  method as well the Collector object no longer packagers Logger instance with it but only has LoggerOption under set.LoggingOptions
Reference:
https://github.com/open-telemetry/opentelemetry-collector/blob/06db057f8ca3cea24ee71b77fffff1b2420d4e07/service/collector.go#L74
https://github.com/open-telemetry/opentelemetry-collector/blob/main/CHANGELOG.md#-breaking-changes--7

Can we close this @dmitryax & @cpheps ?

**Comment by dmitryax** [comment]
Thanks @sakshi1215. Closed
