### ISSUE TITLE
Cannot create a Timestamp with Zero value

### ISSUE THREAD

**Issue by danelowe** [open-telemetry/opentelemetry-collector#5102]
**Describe the bug**

I need to create a timestamp that has a Zero value in order to export correctly to Google Cloud

https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/b068af9a94200ed9c49d58f16817ea6d3066e6e6/exporter/collector/metrics.go#L740

Unfortunately, The timestamp uses an unsigned integer from Unix epoch, which means we can't simply create a Timestamp before 1970.

https://github.com/open-telemetry/opentelemetry-collector/blob/6f4057bddd5c57ce1078cd0c9dc48c80f20f60a5/model/internal/pdata/timestamp.go

**Steps to reproduce**

```
tsZero := pdata.NewTimestampFromTime(time.Time{})
log.Println(tsZero.AsTime().IsZero())
```

**What did you expect to see?**
Running the code above should return true

**What did you see instead?**
Running the code above returns false

**What version did you use?**
Version: 0.47.0

**What config did you use?**
NA

**Environment**
OS: macOS Big Sur, running in scratch docker after compiling for linux amd64
Compiler: go version go1.18 darwin/arm64

**Comment by bogdandrutu** [comment]
I think this is an issue in the Google implementation. /cc @dashpole

**Comment by dashpole** [comment]
Note that because of https://github.com/open-telemetry/opentelemetry-collector/issues/4967, it isn't possible to use the new collector metrics exporter, since it is behind a feature gate.  It does look like a potential issue, though.

@danelowe what are you trying to accomplish?

**Comment by dashpole** [comment]
@bogdandrutu it does look like there is something strange going on with the zero time:

```golang
var ts time.Time
// pass
assert.Zero(t, ts.UTC())
// pass
assert.True(t, ts.IsZero())
timestamp := NewTimestampFromTime(ts)
// Fail: Should be zero, but was 1754-08-30 22:43:41.128654848 +0000 UTC
assert.Zero(t, timestamp.AsTime().UTC())
// Fail: Should be true
assert.True(t, timestamp.AsTime().IsZero())
```

**Comment by dashpole** [comment]
So our exporter should use `timestamp == 0` instead of `timestamp.AsTime().IsZero()`

**Comment by jpkrohling** [comment]
Having a function with the same name as the one from the stdlib, but with different behavior, is not a very good user experience, IMO. Perhaps "IsInitialized" or "IsSet" would be better?

**Comment by bogdandrutu** [comment]
@djaglowski to check if a simple `pdata.Timestamp == 0` works.

**Comment by bogdandrutu** [comment]
@danelowe you can do:

```golang
tsZero := pdata.Timestamp{}
```

**Comment by djaglowski** [comment]
This comparison works of course. 
```go
var ts pdata.Timestamp
ts == 0 // true
```

---

I agree there is a usability issue here. `time.Time` and `pdata.Timestamp` use zero values that are _actually_ different times, but their zero values are meant to represent the same thing (uninitialized) in virtually all meaningful cases.

Knowing this, we could consider converting `time.Time`'s zero value to `pdata.Timestamp`'s zero value in `NewTimestampFromTime`, and doing the opposite in `AsTime`. There's a performance cost (tiny but frequent), but I suspect the bigger question is whether this kind of interpreted conversion will introduce other usability problems. I am curious what others think about this idea.

```go
// NewTimestampFromTime constructs a new Timestamp from the provided time.Time.
func NewTimestampFromTime(t time.Time) (ts Timestamp) {
	if t.IsZero() {
		return
	}
	return Timestamp(uint64(t.UnixNano()))
}

// AsTime converts this to a time.Time.
func (ts Timestamp) AsTime() (t time.Time) {
	if ts == 0 {
		return
	}
	return ts.asLiteralTime()
}

// asLiteralTime converts this to a time.Time without regard for zero values.
func (ts Timestamp) asLiteralTime() time.Time {
	return time.Unix(0, int64(ts)).UTC()
}

// String returns the string representation of this in UTC.
func (ts Timestamp) String() string {
	return ts.asLiteralTime().String()
}

// timestamp_test.go - Passes
func TestZeroTimestamp(t *testing.T) {
	var noTime time.Time
	var noTimestamp Timestamp
	assert.Equal(t, noTimestamp, NewTimestampFromTime(noTime))
	assert.Equal(t, noTime, NewTimestampFromTime(noTime).AsTime())
	assert.Zero(t, NewTimestampFromTime(time.Unix(0, 0).UTC()))
	assert.Equal(t, "1970-01-01 00:00:00 +0000 UTC", Timestamp(0).String())
}
```

**Comment by bogdandrutu** [comment]
@djaglowski despite the fact that we implement or not the proposed change, the fact that users are doing Timestamp.AsTime.IsZero() is very bad and way more latency is added there than the proposed change. How can we fix that? FYI: this proposal does not fix that, and that should be our focus, to avoid that unnecessary conversion.

**Comment by djaglowski** [comment]
> what is the part that makes people not do this?:
>
> tsZero := pdata.Timestamp{}

Answering from a usability point of view, in my case:
- I already had a `time.Time`, which may or may not have been initialized.
- I needed to set the `pdata.LogRecord.Timestamp` field using the `time.Time` value I already had.
- It seemed obvious that I should use the constructor that creates what I need from what I have:
  - `myLogRecord.Timestamp = pdata.NewTimestampFromTime(myTime)`. 
  - The mistake has now been made because I unknowingly set the value to nonsense, as far as `pdata.Timestamp` is concerned.
- I did not know the implementation of `pdata.Timestamp`. I just assumed that because there is a constructor, this is just some equivalent representation that can preserve and convey basic things about the `time.Time` that I started with, like "is this nil?" and "what time is it?".
  - (Never assume, but it is natural to do when an API appears to make it easy for you.) 

So, at least in my case, the difficulty in figuring out how to check if `pdata.Timestamp == 0` was only because it was already too late.

---

I think what I proposed would solve the problem I ran into, but if we want to make sure people don't make the same mistake, then I think there shouldn't be such a tempting constructor like `NewTimestampFromTime`. 

I don't know if changing the name to `UnixTimestamp` would have helped me either. I did not know until this issue that the zero value of `time.Time` is not the epoch, so I still would have assumed that the zero values of both representations were _actually_ the same.

**Comment by bogdandrutu** [comment]
> I did not know until this issue that the zero value of time.Time is not the epoch

I found that very confusing as well when I first realized... I remember initially we had that zero `time.Time` translates to 0 unix, but that is not necessary ok.. It makes `time.Time{} == time.Unix(0, int64(0)).UTC()` which is not the case.  You are breaking this assumption https://github.com/open-telemetry/opentelemetry-collector/blob/c51773abf579854c8656ea2a70609a9348fbca16/model/internal/timestamp_test.go#L35

Also if we do that "zero" conversion, we had a problem with protobuf conversion (there are places where people are doing `timestamppb.New(pdata.Timestamp.AsTime())`, see  https://github.com/protocolbuffers/protobuf-go/blob/v1.28.0/types/known/timestamppb/timestamp.pb.go#L201

**Comment by bogdandrutu** [comment]
Closing this, since the option to create a zero timestamp is there. Feel free to propose API improvements in a separate issue/pr
