### ISSUE TITLE
metrics : what is the difference between StartTimestamp and Timestamp ?

### ISSUE THREAD

**Issue by deathwarrior60** [open-telemetry/opentelemetry-collector#5732]
Hello,

We are trying to send metrics from a F5 to opentelemetry collector using otlp receiver then send it to Cortex.
But we can't see any datapoint in cortex.
We tried the logging exporter to see what we are trying to send, here's the output :
```
Metric #477
Descriptor:
     -> Name: clientSslProfiles_cipherUses_md5Digest
     -> Description: clientSslProfiles.cipherUses.md5Digest
     -> Unit: 1
     -> DataType: Sum
     -> IsMonotonic: false
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE
NumberDataPoints #0
StartTimestamp: 2022-07-21 15:01:04.217999872 +0000 UTC
Timestamp: 1971-11-05 12:35:05.138741344 +0000 UTC
Value: 0.000000
```

We think the issue is link to the timestamp not being correct.
Could you explain what is the difference between Timestamp and StartTimestamp ?

Thanks in advance
Regards

**Comment by mx-psi** [comment]
StartTimestamp is the point in time in which the timeseries started, you can read more about it at the specification: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md#temporality

AIUI this point is not valid because, if StartTimestamp is present, it must happen before Timestamp

**Comment by deathwarrior60** [comment]
Thanks for your feedback.
It's more clear for me now.

It seems to be an error on F5 side : https://github.com/F5Networks/f5-telemetry-streaming/issues/209
