### ISSUE TITLE
Test: investigate skipped tests on OC receiver

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#576]
These are being skipped since OpenCensus collector we should either fix or remove them.

```terminal

=== RUN   TestExportProtocolConformation_metricsInFirstMessage
--- SKIP: TestExportProtocolConformation_metricsInFirstMessage (0.00s)
    opencensus_test.go:233: Currently disabled, this test is flaky on Windows. Enable this test when the following are fixed:
        Issue https://github.com/census-instrumentation/opencensus-service/issues/225

=== RUN   TestReceiver_endToEnd
--- SKIP: TestReceiver_endToEnd (0.00s)
    opencensus_test.go:49: This test is flaky due to timing slowdown due to -race. Will reenable in the future

=== RUN   TestAcceptAllGRPCProtoAffiliatedContentTypes
--- SKIP: TestAcceptAllGRPCProtoAffiliatedContentTypes (0.00s)
    opencensus_test.go:213: Currently a flaky test as we need a way to flush all written traces

```

**Comment by JingboWangGoogle** [comment]
Hi, I am new to OpenTelemetry, and want to try a good first issue. For this one, how do you reproduce the problems here. When I run these tests, they seem to be running ok.

**Comment by bogdandrutu** [comment]
@JingboWangGoogle remove the "skip" from the beginning of the test, if passes then just send the PR :)

**Comment by JingboWangGoogle** [comment]
@bogdandrutu Thanks for the information! I actually wanted to take a shot at this to get familiar with the process and to get myself started as a contributor before my main contribution in the metrics transform processor https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/processor/metricstransformprocessor, but instead, I resolved this one https://github.com/open-telemetry/opentelemetry-collector/issues/557. Thanks for the assignment, but I would actually leave this one for other contributors who want to get started with a good first issue :)

**Comment by AzfaarQureshi** [comment]
Hey, is this free to pick up? I'm also an intern (AWS) who's looking for a good first issue 😂

**Comment by AzfaarQureshi** [comment]
Hi, I started doing some investigation into these tests. The issue behind the second test (`TestReceiver_endToEnd`) has been resolved so it's already re-enabled in the code. 

Had some questions about the `TestAcceptAllGRPCProtoAffiliatedContentTypes` test [here](https://github.com/open-telemetry/opentelemetry-collector/blob/master/receiver/opencensusreceiver/opencensus_test.go#L211). The skip message says the test is flaky because  we need a way to flush all written traces. Since the block of code was written 2 years ago, I was wondering if there have been any changes since which allow for traces to be flushed? If not, is does adding this behaviour fall under the purview of this issue? 

The issue also mentions we should either fix these tests or remove them. What would the criteria be to determine if we should remove these tests instead? Thanks for the help! 😃

**Comment by tigrannajaryan** [comment]
>The issue also mentions we should either fix these tests or remove them. What would the criteria be to determine if we should remove these tests instead?

Remove if fixing is too costly (I'd say if it requires more than a few hours of work then it is not worth it).
