### ISSUE TITLE
While working with ImmutableSlices found them very expensive

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#5859]
Majority of the use-cases to work with the new `ImmutableSlices` especially in the metrics side were related to updating some bucket counts or bucket bounds. In all these cases there was a need to update an existing slice, which is very expensive with the current approach.

I propose that we change from "Immutable[Bytes|Uint64|...]Slice" to a "[Bytes|Uint64|...]Slice" which has an api to allow set a value at an index "SetAt(i, val)". 

/cc @dmitryax can you look into this and make sure my proposal makes or does not make sense?

**Comment by dmitryax** [comment]
@bogdandrutu This goes against the decision that we made in https://github.com/open-telemetry/opentelemetry-collector/issues/5263 . It means that we will need to copy the slices when the owner pdata objects are copied. 

If we go this route, I'm not sure what are we gaining by wrapping the slices at all. To fix https://github.com/open-telemetry/opentelemetry-collector/issues/5263 from the state where we were initially, we could've just make defensive copping of the slices in the setters. It seems like wrapping it in plain `[Bytes|Uint64|...]Slice` with `SetAt` just limits the API of the native go slices with no additional benefit . Or am I missing some benefits?

**Comment by bogdandrutu** [comment]
What do you mean, I am a bit confused. The proposal is not to return a golang slice which has the problem that you describe, but to return a `ByteSlice` struct similar to all other `XSlice` structs that we have in the `pdata`

**Comment by dmitryax** [comment]
> The proposal is not to return a golang slice which has the problem that you describe, but to return a ByteSlice struct similar to all other XSlice structs that we have in the pdata

The point of `pdata` is to forbid direct access to underlying proto structs to allow us potential changes in them, right? There are no changes that we can expect in underlying primitive types to abstract them for the same reason. To fix https://github.com/open-telemetry/opentelemetry-collector/issues/5263, we could've just added a defensive copying in the owner objects setters, e.g. `HistogramDataPoint.SetBucketCounts`. The same defensive copying must be done if we wrap the primitive slices in any other structure. Defensive copying in getters can be also considered but is not really required for https://github.com/open-telemetry/opentelemetry-collector/issues/5263.

Instead, we went with this `ImmutableXSlice` approach to be able to avoid copying of the slices when owners are copied, e.g. we can reuse the same the same `BucketCounts` object when `HistogramDataPoint` is copied. I'm not sure if it's a significant enough benefit to keep the immutable slice wrappers, but looks like it's the only benefit.

At the same time, I don't see a big benefit in wrapping primitive slices in `[Int|Byte...]Slice `, other than for consistency with other `XSlice` structures.

Let's see how the user interface will be improved. For example, in order to increment all the `BucketCounts` in `HistogramDataPoint` currently user would need to do the following (Option 1):

```go
bcs := hpd.BucketCounts().AsRaw()
for i, v in range bcs {
    bcs[i] = v+1
}
hpd.SetBucketCounts(pcommon.NewImmutableUInt64Slice(bcs))
```

With your suggestion it will be (Option 2)

```go
bcs := hpd.BucketCounts()
for i := 0; i < bcs.Len(); i++ {
    bcs.SetAt(bcs.At(i) + 1)
}
```

Option 3: primitive type (+ defensive copying in setters) implementation:

```go
bcs := hpd.BucketCounts()
for i := 0; i < bcs.Len(); i++ {
    bcs[i]++
}
// The next line is only required if we want to have defensive copying on getters, which is not strictly required.
hpd.SetBucketCounts(bcs)
```

The option 3 (given no defensive copy in getters) seems the most convenient for user, but we lose ability to reuse the slices when we copy the owner objects as currently possible with Option 1.

Please let me know if it makes sense or I miss something.

**Comment by bogdandrutu** [comment]
You can see that from performance perspective:

Both options beside 2 need at least one copy of the slice, probably 2. That is the reason I call them expensive

**Comment by dmitryax** [comment]
> Both options beside 2 need at least one copy of the slice, probably 2. That is the reason I call them expensive

I don't get why Option 2 doesn't need a copy of the slice. At least, it needs a defensive copy on setter as all other options, right?

Speaking about copies on getters, the options 2 and 3 are similar. Option 3 can go without copy on getter, in that case performance-wise Option 2 and 3 are the same. The only benefit of Option 2 in this case is that making `bcs.SetAt(0, 1)` calls are maybe more explicit then `bcs[0] = 1` giving users a feeling that they mutate `pdata` objects not just random slices. But at the same time Option 2 limits the slices API.

And again, if we switch back to Option 2 or 3, we lose ability to reuse the same slice when data is copies -> potential performance degradation. So we cannot say that Option 2 or 3 will always provide better performance overall. It's degraded when changes need to be done to the slices, but improved when pdata objects are copied. Not sure which use case is more common.

**Comment by dmitryax** [comment]
@bogdandrutu I examined all the usages in the contrib and found the following use cases:

### 1. Create a new slice from a given primitive slice

  - Occurrences: 16
  - Modules:
    - pkg/stanza
    - pkg/telemetryquerylanguage
    - pkg/translatror/opencensus

This use case is good for the existing approach (Option 1). If we go with the Option 2, we would need to introduce the same setter with defensive copying, switching to NewSlice -> SetAt would make the code pretty cumbersome.

### 2. Create new slice from individual values

  - Occurrences: 5
  - Modules:
     - pkg/translatror/opencensus
     - processor/spanmetrics
     - receiver/prometheus

This use case requires an extra slice allocation for Option 2 and 3. The NewSlice -> SetAt approach from Option 3 would be the best approach without affecting the user experience.

### 3. Update slice by individual items
  - Occurrences: 4
  - Modules:
    - processor/cumulativetodelta
    - procesor/metrictransform

This use case is similar to 2 but requires 2 extra slice allocations for existing approach (Option 1). The SetAt method from Option 2 would help to avoid the allocations.

### Summary

For the most of usages in contrib, the existing approach works well. For use cases 2 and 3, the Option 2 works the best. But if we want to go with the Option 2, we should still introduce a way to copy a primitive slice into the wrapper otherwise we complicate the API for the use case 1.

Let me know WDYT. I can quickly prototype the option 2 both core and contri

**Comment by bogdandrutu** [comment]
Things to do in a followup PR:

- [ ] Copying can be done in-place to save allocations.
- [ ] No way of increasing the capacity or length. We can discuss about that API.
- [ ] Add CopyTo/MoveTo and remove the copy logic from the parent's CopyTo.
