### ISSUE TITLE
Programatically configure collector

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-collector#601]
We are extending OTEL collector in Jaeger project. The use case we have is to run the collector without the configuration file. This allows smoother migration from Jaeger collector to new Jaeger OTEL collector. Jaeger can be executed without any configuration or the configuration can be provided by flags, env vars., file (all is managed by viper)

When the configuration file is missing the default configuration would be used. We were able to bind Jaeger flags to OTEL command and use them as default values in OTEL config  (e.g. Elasticsearch exporter).

To support this use case we need to programmatically configure OTEL collector, for instance enable specific receivers, processors and exporters.

**Comment by flands** [comment]
`--config` can be passed today. Agreed a default configuration should be available -- is that the only ask here?

**Comment by pavolloffay** [comment]
> --config can be passed today. Agreed a default configuration should be available -- is that the only ask here?

I know that `--config` can be passed today and the collector fails if the config is missing or invalid. In Jaeger OTEL build we want to run the collector when config is missing and programmatically configure it.

**Comment by pavolloffay** [comment]
Also, I am happy to submit a PR. First I just want to make sure that we agree on this proposal.

**Comment by flands** [comment]
In OC we had options to enable things: https://github.com/census-instrumentation/opencensus-service#collector-usage. Is the ask to re-add this functionality?

**Comment by pavolloffay** [comment]
It could work, but a purely programmatic API on the https://github.com/open-telemetry/opentelemetry-collector/blob/master/service/service.go would be better otherwise we will have to hack around the `os.Args`.

**Comment by flands** [comment]
Got it -- will wait for @tigrannajaryan and @pjanotti to weigh in

**Comment by owais** [comment]
What if the main entry point took an additional argument that was either raw bytes or a parsed config struct? The service would use this argument as config instead of loading it from the disk. A build can then programmatically generate a config yaml, marhsal it to bytes and hand it over to the main service entry point. That would result in minimal changes to the service while allowing custom builds to implement a variety of config plugins on top. This would allow supporting any config option that collector support through alternate mechanisms without having to update the collector to add new flags, env vars etc. 

Essentially, this line https://github.com/open-telemetry/opentelemetry-collector/blob/master/cmd/otelcol/main.go#L44 would look like

```go
        yamlConfigBytes = readOrAutoGenerateConfig()
	svc, err := service.New(factories, info, yamlConfigBytes)
```

**Comment by pavolloffay** [comment]
It sounds reasonable. I am wondering whether there is configuration struct/type which could be passed instead of the bytes to make it more type-safe.

**Comment by tigrannajaryan** [comment]
We can pass `configmodels.Config` to `service.New`. It is type-safe and is the full representation of the config.
