### ISSUE TITLE
Support for updating and merging already running an Opentelemetry Collector 

### ISSUE THREAD

**Issue by kabhanus007** [open-telemetry/opentelemetry-collector#6054]
**General Implementation idea before jumping into feature request**
We have a requirement where we have to implement opentelemetry collector on the managed and unmanaged environment and to keep both environments in sync, we are following opamp spec but with modification. As we have various agents to take care of, our implementation consists of detached client which will work with any type of collectors, so kind of a model Agent(collector ex: otel collector) <-> client pod(opamp spec client) <-> service pod(opamp spec server) architecture.

**Is your feature request related to a problem? Please describe.**
feature is somewhat related to the problem - [4742](https://github.com/open-telemetry/opentelemetry-collector/pull/4742), and mainly what I am looking is closley related to the example present in this doc - [doc](https://docs.google.com/document/d/1XlDpS8-a4Ds6uoe6C6WgO8mCpDaQNufcHSEmBpiCdI0/edit), so, I need something where if you have your Agent collector already running with some configuration, and if you received some additional config through client pod, then it should merge and update the running collector,  

**Describe the solution you'd like**
ex: if I have Prometheus exporter running which sent some config from service to client related to prometheus exporter, then it should update the running otel collector and those stuff to it.

**Comment by bogdandrutu** [comment]
Sorry, it is a bit unclear the "feature request" part of this issue.

If the ask is to support configuration "reloading", we decided for the moment to not support a "hot" reloading, and only allow for restart reloading, shutdown + start with the new configuration. The reason is because the collector configuration is very complex and involves multiple components and will be very hard to reload the configuration without reconstructing the pipelines, etc.

**Comment by kabhanus007** [comment]
thanks got it.
