### ISSUE TITLE
Add service.name resource attribute to the collector's own telemetry

### ISSUE THREAD

**Issue by jlegoff** [open-telemetry/opentelemetry-collector#6136]
**Is your feature request related to a problem? Please describe.**

The opam spec [states](https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionidentifying_attributes) that an agent should have the following identifying attributes:
* service.name
* service.namespace
* service.version 
* service.instance.id 
* any other attributes that are necessary for uniquely identifying the Agent's own telemetry.

At the moment, the collector's own telemetry don't include these.

**Describe the solution you'd like**
The collector should include the above attributes - `service.namespace` and `service.instance.id` should probably be configurable. I'm not sure what the default values should be.

**Describe alternatives you've considered**
I've [suggested](https://cloud-native.slack.com/archives/C01N6P7KR6W/p1663680351659209) in slack a specific resource type might be created for agents, but the consensus seems to be that the collector is a service.

**Comment by tigrannajaryan** [comment]
>At the moment, the collector's own telemetry don't include these.

This is partially correct. Collector does include `service.version` and `service.instance.id` already. `service.name` is indeed missing and based on today's SIG discussion should be added. 

Collector also allows to specify arbitrary attributes to include in its own telemetry using `resource` key under the `telemetry` key of the config. This allows the user to define `service.namespace` and any other attributes and also allows overriding `service.instance.id`.

The only thing I believe is really missing is that `service.name` should be by default included in own telemetry. I would expect it to be set to the FQDN, e.g. "io.opentelemetry.collector".

**Comment by tigrannajaryan** [comment]
Some findings for posterity: I have been testing how Collector generates its own metrics using prometheusreceiver to collect them and was surprised to discover that `service.name` was included as Resource attributes on the collected metrics. I was surprised since I didn't expect this. However, after some digging I found that prometheusreceiver sets the `service.name` [equal to the configured job name](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4d376d0d928dd82601f72abe432d763fb66610af/receiver/prometheusreceiver/internal/prom_to_otlp.go#L53). 

So, we still need to add the `service.name` as a Resource attribute, even if the prometheusreceiver overwrites it with the configured job name later (since prometheusreceiver is not the only way we will be collecting our own telemetry in the future).

**Comment by jack-berg** [comment]
> The only thing I believe is really missing is that service.name should be by default included in own telemetry. I would expect it to be set to the FQDN, e.g. "io.opentelemetry.collector".

I don't think it makes sense to use a constant `service.name` in the collector. Perhaps a constant can be used as a fallback, but ultimately I think its a user concern to assign a logical name to the collector as they see fit. Perhaps a new property can be added to the collector YAML config? 

It seems like the desire to use a constant manifests from opamp's usage of `service.name` as an agent type identifier. I think `service.name` is being incorrectly used in this regard, and opened [opamp-spec #131](https://github.com/open-telemetry/opamp-spec/issues/131) to discuss it.

**Comment by tigrannajaryan** [comment]
> I don't think it makes sense to use a constant `service.name` in the collector. Perhaps a constant can be used as a fallback, but ultimately I think its a user concern to assign a logical name to the collector as they see fit. Perhaps a new property can be added to the collector YAML config?

Yes, that's what [the PR](https://github.com/open-telemetry/opentelemetry-collector/pull/6152) does. We define a default is which can be overridden by the end user using the config file.
