### ISSUE TITLE
Add support for config validation to confmap providers

### ISSUE THREAD

**Issue by amdprophet** [open-telemetry/opentelemetry-collector#6161]
**Is your feature request related to a problem? Please describe.**
I've been working on an OpAmp confmap provider which:
1. Checks local cache for config.
2. Connects to OpAmp.
3. Creates a goroutine to listen for config updates. If a config is received, it is persisted to the local cache and a restart is triggered via the watcher.
4. If a config was found in the local cache, return it as a confmap.Retrieved.
5. If no config was found in the local cache, wait for the first config from OpAmp and return it as a confmap.Retrieved. Does not trigger a restart.

I'd like to validate the config retrieved from OpAmp before persisting it to disk to avoid storing a bad config, preventing the collector process from starting. After some investigation it appears that a list of factories are needed for config unmarshaling, necessary for config validation. This prevents confmap providers from performing validation as they do not have access to the list of factories.

**Describe the solution you'd like**
Some way of running validation against a retrieved config in a confmap provider. Possibly giving factory access or a validation callback to confmap providers.

**Comment by Aneurysm9** [comment]
I'm not sure it is possible for an individual confmap provider to validate the configuration it provides.  It is possible that a configuration is only valid once multiple sources are merged together as each provides a part of the whole.  If any sort of last-known-good configuration caching should take place it probably belongs in the service where the complete configuration is available.

**Comment by tigrannajaryan** [comment]
There is a fundamental limitation in the Collector that prevents implementation of validation in a robust manner: the components may fail asynchronously due to bad config after the component parses and accepts the config, the Start() of the component returns true and Service's start sequence is complete and all is running seemingly well.

Due to this limitation it is impossible to perform a validation that guarantees that the config is not going to cause the Collector to fail.

Now, if we are happy to live with this limitation then we can think about how to perform the validation step. It may need to be performed by the Service after all Providers return their part of the config and the final config is formed. One of the approaches is to have a callback in the Provider that is called after Service validates the config and which also informs the Provider about the final effective config (the later capability is great for OpAMP).

As for the fundamental limitation. I don't see an easy way to remove this limitation. However, if we embrace it then perhaps one other thing we can do is to recognize that we fail due to bad config and revert back to the last known good config. The hard part is how we recognize that failure is due to config and not something else. This is likely a separate issue to discuss.

cc @bogdandrutu

**Comment by tigrannajaryan** [comment]
So perhaps something like this can be added to Provider interface:

```go
type Provider interface {
  ...
  // ConfigChanged is called if any Provider triggers the WatchFunc, after all configuration is
  // merged and validated and before the Service is restart with the new config. 
  // effectiveConfig reflects the current total effective configuration of the Service.
  // err is set if config updating failed for whatever reason (e.g. the new config did not validate).
  // If an error happens effectiveConfig reflects the previous (unchanged) config, not the config
  // that failed.
  ConfigChanged(effectiveConfig string, err error)
}
```

**Comment by portertech** [comment]
@tigrannajaryan how would a particular provider know its "at fault" when the effective config is the result of more than one provider?

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan how would a particular provider know its "at fault" when the effective config is the result of more than one provider?

It won't if we go with my proposal. However, why does the Provider need to know who in particular is at fault?

**Comment by tigrannajaryan** [comment]
> If any sort of last-known-good configuration caching should take place it probably belongs in the service where the complete configuration is available.

Conceptually this sounds right but in practice it may be hard to do this within the existing configuration framework. 

We delegated all responsibility to read config files and deal with the filesystem to fileprovider. The Service currently knows nothing about the filesystem. We would need to make Service aware of the filesystem, which is a problem because that awareness itself requires some sort of configuration (at least the user needs to be able to specify the directory to store the cache in) and that creates a circular problem (to prepare the config I need access to the config first) or you will need to create another "config of config" concept.

**Comment by amdprophet** [comment]
@tigrannajaryan I like the proposed idea of notifying configmap.Providers if the final merged config is valid. It will solve the issue of knowing whether to persist the received configuration, from OpAmp, locally. We're going to explore moving the effective config reporting to OpAmp elsewhere as it seems out-of-scope for configmap.Providers to have access to the merged config.
