### ISSUE TITLE
Split `component` into its own module

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#6187]
From @bogdandrutu:

> One question is if we want to have this package OR move everything into `go.opentelemetry.io/collector/CMP` (where CMP is one of receiver/processor/exporter/extension).

**Comment by codeboten** [comment]
is there an agreement on how to proceed with this split? I guess if we were to split all the type specific stuff out of component, we'd end up with some amount of repetition in the name:

```
import "go.opentelemetry.io/collector/exporter"

exporter.ExporterFactory
exporter.Exporter
exporter.TracesExporter
```
instead of what it is currently:

```
import "go.opentelemetry.io/collector/component"

component.ExporterFactory
component.Exporter
component.TracesExporter
```

It would be possible to remove some of that repetition, but I'm not sure what we would call the `TracesExporter` for example to make it less repetitive. I do like having the components packages separated per type to only include what's relevant in each one, and reduce the amount of code imported for each one.

@open-telemetry/collector-approvers any thoughts?

**Comment by Aneurysm9** [comment]
We could eliminate a bunch of that repetition in the per-component case, I think:

```
import "go.opentelemetry.io/collector/exporter"

exporter.Factory
exporter.Exporter
exporter.Traces
```

Not sure that there's a better name for `exporter.Exporter`, but [`url.URL`](https://pkg.go.dev/net/url#URL) exists and the world hasn't come to an end. v0v

**Comment by dmitryax** [comment]
I don't believe we can move things from `component` to `go.opentelemetry.io/collector/[receiver|processor|exporter|extension]` at least because of `component.Host`. I'm not 100% sure we need to extract those parts from `component`, but, if we want to, maybe we can have the following packages instead:
```
go.opentelemetry.io/collector/component/exporter
go.opentelemetry.io/collector/component/receiver
go.opentelemetry.io/collector/component/processor
go.opentelemetry.io/collector/component/extention
go.opentelemetry.io/collector/component/host
```
And it's not that simple, we will also need to move other things (like `component.Kind/Component`) since there are interdependencies with `Host`.

**Comment by codeboten** [comment]
After further digging into this, the `Host` complication makes the split per component impractical. My plan is to keep `component` as a single package containing the different component types within it.

**Comment by bogdandrutu** [comment]
I made a prototype, and I think it is simple to do the split, see https://github.com/open-telemetry/opentelemetry-collector/pull/6552

The main idea behind is that Host depends on "Extension" and "Exporter" interfaces which are useless anyway, they can be replaced by using Component (since they are simple renames for Component anyway), something like https://github.com/open-telemetry/opentelemetry-collector/pull/6553

**Comment by dmitryax** [comment]
I submitted a follow-up issue for the split suggested by @bogdandrutu https://github.com/open-telemetry/opentelemetry-collector/issues/6578
