### ISSUE TITLE
log.Fatal vs returning errors

### ISSUE THREAD

**Issue by nilebox** [open-telemetry/opentelemetry-collector#619]
Collector codebase currently extensively uses `log.Fatal` calls at any stage of the startup. 
e.g. [service.go](https://github.com/open-telemetry/opentelemetry-collector/blob/master/service/service.go) currently contains 12 such calls.

While there is nothing wrong with terminating application when it fails to initialize properly, the number of points triggering termination should be limited.

One particular case where this can cause issues is if at any stage of application startup we use `defer` statement, which doesn't get called upon `os.Exit()` (see https://golang.org/pkg/os/#Exit) invoked by `log.Fatal`.

Also, if someone is using Collector's code programmatically (see #601 for example), they may prefer to handle fatal errors themselves and decide if their application requires immediate termination.

I suggest a rule that `log.Fatal` (or other means of terminating application) should not be used outside the `main` package (and tests).

This can easily be fixed via replacing `log.Fatal` calls with returning errors in https://github.com/open-telemetry/opentelemetry-collector/blob/ea761567bdb475ef86e89416312db1df9db7e809/service/service.go#L145 and similar places.

---

See https://dave.cheney.net/2015/11/05/lets-talk-about-logging
> Don’t log at fatal level, prefer instead to return an error to the caller. If the error bubbles all the way up to main.main then that is the right place to handle any cleanup actions before exiting.

**Comment by flands** [comment]
Failing early is by design, but agreed termination points should be limited. @tigrannajaryan thoughts?

**Comment by tigrannajaryan** [comment]
Yes. As soon as a piece of code can be imported and used as a library `log.Fatal` or any other form of exiting the process directly from library code is bad practice. The caller (main) should ultimately decide what to do as a result of the error.

`Application` is now part of our extensibility story and we encourage importing it and using in custom builds. I agree `log.Fatal` and any other process exits should be converted to errors where possible. Note that it may not be as easy as converting `log.Fatal` to `return err`. Some functions can't return errors because that's their expected signature, so there may be some refactoring needed.

I agree with the philosophy though. I would even make this part of our [Coding Guidelines](https://github.com/open-telemetry/opentelemetry-collector/blob/master/CONTRIBUTING.md#coding-guidelines). We have a section about startup and logs there, would be good to specifically call this case out.

Note that `Application.ReportFatalError` that is intended to be used by components is already implemented correctly, it initiates proper shutdown sequence.

**Comment by nilebox** [comment]
> Some functions can't return errors because that's their expected signature, so there may be some refactoring needed.

It seems that changes in `Application` won't require signature changes, since https://github.com/open-telemetry/opentelemetry-collector/blob/5334b3a8ff0825671a88b3c08d0378c3be159706/service/service.go#L380 already returns error.

So what we need to do there is to replace `Run` with `RunE` in https://github.com/open-telemetry/opentelemetry-collector/blob/5334b3a8ff0825671a88b3c08d0378c3be159706/service/service.go#L115 which will allow us to propagate errors back to `Application.Start`.
