### ISSUE TITLE
Adding new signal is a breaking change for component.[Exporter|Processor|Receiver]Factory

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#6505]
This is part of a bigger discussion in https://github.com/open-telemetry/opentelemetry-collector/issues/4705 

If we release `component` 1.0 with the current design of the component factories, we will need to make a major release every time we add another signal type because it'll be a breaking change for the interfaces. This might be something that we want to go with. But I would like to consider other ideas.

cc @bogdandrutu @codeboten @Aneurysm9

**Comment by codeboten** [comment]
Would it be breaking? Adding new signals should be ok no?

**Comment by codeboten** [comment]
ah right... changing the interface would break anyone implementing it 🤔

**Comment by bogdandrutu** [comment]
This is not true :)) Because I designed this in a way that annoys other people, but helps us keeping this flexibility. See https://github.com/open-telemetry/opentelemetry-collector/blob/727ca568c38b6682a8ed89d17a94b2ab14895915/component/component.go#L161 which makes the interfaces extensible since there are no external dependencies.

**Comment by dmitryax** [comment]
Oh right! I missed `unexportedFactoryFunc`. Sorry for the confusion. Closing the issue
