### ISSUE TITLE
Confmap does not honor `Unmarshal` methods on embedded structs

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#6671]
**Describe the bug**

The confmap `Unmarshal` method honors the `Unmarshal` methods on field structs but does not do so on embedded structs.

**Steps to reproduce**

See #6668 for an example

**What version did you use?**

Happens as of fb0842a5a200ad1bc7475a4f69baa994310792a4

**Comment by mx-psi** [comment]
I spent a bit working on this but I am not sure how to fix it. It looks related to mitchellh/mapstructure/issues/166, so maybe @jefchien has some ideas?

**Comment by jefchien** [comment]
This seems like a different issue. When mapstructure tries to decode a map into a struct, it has this loop that handles the squashing of the embedded struct fields https://github.com/mitchellh/mapstructure/blob/main/mapstructure.go#L1340. Since it happens in this step, it doesn't try to decode the embedded struct as a whole and only calls `decode` on the fields within. So, the decode hook, which is used to assert/call the `Unmarshaler` interface (https://github.com/open-telemetry/opentelemetry-collector/blob/main/confmap/confmap.go#L271) never sees the embedded struct.

**Comment by mx-psi** [comment]
I checked this with @gbbr and we don't see a way to fix it short of re-implementing the `Decode` method itself (which means a few thousand lines to maintain). I am tempted to say we mark this as 'wontfix' and just document this limitation clearly: it's annoying and unexpected, but there is a workaround.

**Comment by bogdandrutu** [comment]
In the current `unmarshalerHookFunc` can we iterate over all the fields of the "to" and if a struct field (without name) then we check for unmarshaler... Does that miss something?
