### ISSUE TITLE
Proposal: Passing parameters to configmap providers using URI fragments

### ISSUE THREAD

**Issue by rapphil** [open-telemetry/opentelemetry-collector#6892]
**Is your feature request related to a problem? Please describe.**
Right now it is not possible to pass parameters to config map providers. Up to now this was not an issue. With the recent [PR](https://github.com/open-telemetry/opentelemetry-collector/pull/6683) to include the httpsprovider to the list of supported providers, this is not the case anymore. This provider should have multiple knobs in order to configure the SSL Certificates and the client behavior while communicating with the servers. However, right now this provider is only accepting the system defaults, which will require name validation and to use the system root CA certificates to validate the server certificate. Dealing with the system root CA certificates is quite painful for the case customers are not using certificates issued by a public CA authority. A more flexible alternative is necessary. 

We should provide a mechanism for customers to specify the CA certificate that they want to use to connect to a server, as well as whether they want to validate the hostname of the server against the certificate that is installed on it. This mechanism has to take into account that configuration fragments might be fetched from difference sources, including multiple https servers, each with its own configuration.

This mechanism should also work for any type of config map provider, not only the httpsprovider.

**Describe the solution you'd like**

I would like to pass parameters to config map providers. One proposal in [this comment](https://github.com/open-telemetry/opentelemetry-collector/pull/6683#discussion_r1057820092) is to use URI fragments to store a query string whose values are parsed and interpreted by each config provider.

E.g.: 
```
otelcorecol_linux_amd64 --config="https://example.com/myConfig#?insecure=true&certPath=/path/to/cert" \ 
   --config="https://example.com/anotherConfig#?certPath=/path/to/cert2" \
   --config="file://foo/bar#?watchInterval=60s"
```
URI fragments are not supposed to be evaluated by the server and are processed exclusively in the client-side. This characteristics make the URI fragment a good candidate for passing parameters to the config providers.

One benefit of this approach is that it is explicit that the configurations being applied to the config provider should be applied only to a specific URI as opposed to all URIs of a config provider.

**Describe alternatives you've considered**

1. Command line parameters only
Adding new flags/parameters to the command line was also considered, but there is no design for it. How would we correlate URIs with the configuration that should be applied to it?
2. Special configuration file
Add an extra configuration file which would hold configurations for the config map providers. This file has to be read before any of the other configurations.
Format:
```
<uri>:
   <config>: <config value>
```
E.g.:
```
https://example.com/myConfig:
  caCertPath: /path/to/cert
  isInsecure: true
```
Then the collector would be initiated with:
```
otelcorecol_linux_amd64 --config="https://example.com/myConfig" --confproviders-config=/path/config.yaml"
```

**Additional context:**
https://github.com/open-telemetry/opentelemetry-collector/blob/main/confmap/README.md

**Comment by bogdandrutu** [comment]
I think there is nothing we need to do to support this, and is already supported and that is how was planned.

**Comment by bogdandrutu** [comment]
So this should be closed, since it is not something "new". Unless you want to better document the description of the uri parameter.

**Comment by Aneurysm9** [comment]
I wasn't able to attend the SIG meeting last week, but it seems that there was some confusion on whether this would be an appropriate solution.  I think I agree with @bogdandrutu on this already being supported, but it's not immediately obvious from the initial design doc or the referenced comment that using a URI fragment to convey configuration information is acceptable because the fragment is in the opaque portion of the "`<scheme>:<opaque_data>` format".

**Comment by bogdandrutu** [comment]
I linked the RFC https://www.rfc-editor.org/rfc/rfc3986 in the description, and in the [section 3](https://www.rfc-editor.org/rfc/rfc3986#section-3) fragment is defined.

**Comment by Aneurysm9** [comment]
Note that RFC3986 (and specifically its [discussion of fragment identifier semantics](https://www.rfc-editor.org/rfc/rfc3986#section-3.5)) has been amended by [RFC8820](https://www.rfc-editor.org/rfc/rfc8820#name-uri-fragment-identifiers).  I think that some confusion may arise because we're using the definition of the URI syntax to give structure but not semantics.  I'm good with the definition of config locations as `<scheme>:<opaque data>` and allowing schemes to say that their opaque data can be processed in such a way that the thing that appears to be a URI fragment identifier can be treated as a set of key/value pairs for extracting configuration of the configuration source, but others may not see it that way.

**Comment by mx-psi** [comment]
On the last Collector SIG we decided that we would support this via URI fragments. Can we close this issue as 'wontfix' then or is there remaining work to do on improving our description on the URI format? cc @Aneurysm9 @bogdandrutu

**Comment by mx-psi** [comment]
Bump on my question above @Aneurysm9 @bogdandrutu

**Comment by mx-psi** [comment]
Closing as wontfix per discussion above.
