### ISSUE TITLE
Investigate if golang generics help with interface duplications in the consumer package

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#7051]

**Comment by evan-bradley** [comment]
I've looked into this, and generics could be used to reduce a lot of duplication, but there would be some tradeoffs.

Pretty much all of the code could be deduplicated if we created a `consumer.Consumer[S any]` interface with a type parameter for a specific signal, and a generic `Consume` method to consume that signal. I think it would then make sense to instantiate the type for each signal to make it easy to use. For traces, this would be:

```golang
type Traces = Consumer[ptrace.Traces]

type ConsumeTracesFunc = ConsumeFunc[ptrace.Traces]

var NewTraces = NewConsumer[ptrace.Traces] 
```

The downside of this is that each signal's consumer interface becomes mutually exclusive for a struct to implement, since they all implement `Consume` and Go doesn't support function overloading. So helpers like `consumertest.Consumer` would need to be specific for a signal instead of supporting all signals. This would also expose the generic interfaces from the `consumer` package, which causes the package to have a larger API surface.

I'm unable to find any other way to use generics that meaningfully cuts down on duplication, in part because each consumer interface is only ~20 SLOC.

**Comment by codeboten** [comment]
Can this issue be closed then? Or is there a follow up to document this anywhere?

**Comment by evan-bradley** [comment]
Sorry, I completely missed the notification for this.

I'm fine closing this issue. I can't think of any good place to document this, but if there's somewhere you think would make sense, I'd be happy to do it.

**Comment by codeboten** [comment]
Based on @evan-bradley's findings here, I think we're good to close the issue.
