### ISSUE TITLE
Easy CLA is requesting an additional persons signature in addition to Peter's 

### ISSUE THREAD

**Issue by shillasaebi** [open-telemetry/opentelemetry-collector#7211]
This project asks Peter a signed CLA which he has already done, but the PR also has Lorraine Hagendorf’s account attached to it, and is requesting an additional signed CLA.  Can you please take a look at this and help? Thank you! 

Here is the PR for reference: 

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18726

**Comment by mx-psi** [comment]
The first commit on the PR does seem to have the `omicron` account linked to it https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18726/commits/cc6376dc0a382929665ccadae9ea5664073e0575, so I don't think this is a problem on EasyCLA (if anything it would be on Github's side, though most likely it's something on Peter's local configuration).

In any case, we don't maintain EasyCLA, so if after checking the local configuration this turned out to be an issue on their side please report it on https://github.com/communitybridge/easycla, thanks!
