### ISSUE TITLE
OpenTelemetry collector requiring TLS certificates to export traces

### ISSUE THREAD

**Issue by EricBuist** [open-telemetry/opentelemetry-collector#7219]
Hi,
According to documentation, unless tls.insecure=true, using TLS on an endpoint requires certificate files, which is problematic in case of exporters. Exporters should be able to get the TLS certificate from the server since only the public key is needed to act as a client. But according to documentation, one needs to supply names of certificate files. Of course, TLS servers like OTLP receiver, needs the private key. It is not obvious to figure out how to get the TLS certificate from a server, and super inefficient (at least in my organization) to ask for that; they won't know what I am talking about. Maybe there are commands to copy/paste from somewhere that would download the public key, but that should be done from the OpenTelemetry Collector rather than having users do that. If the TLS public keys are not needed for clients like exporters, that should be stated in the documentation, because at the moment this is misleading.

**Comment by jpkrohling** [comment]
TLS has an identity trust aspect, meaning a client must trust that the server is who it claims to be. For that, the server's cert is signed by an entity (Certificate Authority, CA), which should be trusted by the client at some level. For public-facing servers, the cert's trust chain would include a well-known CA, included into the browser's or OS' "trusted root CA" list.

If your server's cert is signed with a CA trusted by the client, you don't need anything on the collector's exporters other than the `endpoint`.

For infra that is not exposed to the public internet, it's common to have internal CA's signing the certs, or even to have self-signed certs. For those cases, the client might not be able to verify the certs, as it does not know any of the signing entities in the cert's chain. In that case, you need the CA's public key and specify it as part of `ca_file`, or the actual expected cert used by the server as `cert_file`. Those will be used to verify that the cert provided by the server can be trusted.

**Comment by jennydaman** [comment]
Please re-open this issue.

@jpkrohling your response does not address the point raised by @EricBuist. As you have described yourself, for the client "you need the CA's public key." In [public-key cryptography](https://en.wikipedia.org/wiki/Public-key_cryptography), the client does _not_ need the private key.

The problem is that opentelemetry-collector requires public _and_ private key, even when it is acting as a client (exporter configuration).

https://github.com/open-telemetry/opentelemetry-collector/blob/0f6c304b2cb51d98623a3e64364012882068da78/config/configtls/configtls.go#L332-L333
