### ISSUE TITLE
Should the logging exporter be renamed?

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#7769]
Please vote in the comment below https://github.com/open-telemetry/opentelemetry-collector/issues/7769#issuecomment-1601379447

**Comment by atoulme** [comment]
Let's rename it before we mark the component away from development - See #7768

**Comment by codeboten** [comment]
Fwiw, we [moved away](https://github.com/open-telemetry/opentelemetry-collector/commit/2363b528407133471a9d32468b1fe5286932fd1f) from from loglevel back in october and users are still running into issues w/ this due to documentation floating around that uses the incorrect config. 3 releases may not be enough for this change

**Comment by astencel-sumo** [comment]
I agree `logging` is not a good name for this exporter. This issue has been raised before, last time in Collector SIG meeting on [December 21, 2022](https://docs.google.com/document/d/1r2JC5MB7GupCE7N32EwGEXs9V_YIsPgoFiLP4VWVMkE/edit#heading=h.tdupcqrlnbe5). Here are two related issues:
- https://github.com/open-telemetry/opentelemetry-collector/issues/3524 from June 2021
- https://github.com/open-telemetry/opentelemetry-specification/issues/1931 from September 2021

If we do decide to rename, does it mean that rather than strictly renaming, we would need to create a new exporter under a different name that would be a copy of the current `logging` exporter, and deprecate the `logging` exporter? Possibly keeping the deprecated one "forever", or at least for a year.

**Comment by codeboten** [comment]
@astencel-sumo we could add a method to the logging exporter to make it instantiable under a different configuration option, something like https://github.com/open-telemetry/opentelemetry-collector/pull/7773

**Comment by DewaldDeJager** [comment]
> 1. Deprecate the go.opentelemetry.io/collector/exporter/loggingexporter module and add some mechanism in ocb to notify users about deprecated modules

I agree with this approach. I'm not sure I agree with wrapping one exporter from the other (as per discussions in the SIG meeting). It feels similar to when the `spanmetrics` exporter was deprecated and replaced by the `spanmetrics` connector. The deprecated component should have no further development and users should be nudged to switch to the new component. The downside of this is that the code will be duplicated initially.

I also agree that it's a good idea for `ocb` to log warnings when trying to include any deprecated modules so that the distribution maintainers can look at replacing it. We should consider logging a warning about any deprecated components when the Collector starts if we don't have that already. This will help the distribution maintainers as their end-users will be nudged to move over to the new component.

**Comment by codeboten** [comment]
@open-telemetry/collector-approvers @open-telemetry/collector-contrib-approvers is `debug` the name we want to go with?

Looking through various otel repos, there's a few different names already for this type of exporter: `stdout` (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk_exporters/stdout.md) & `console` (https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.Console/README.md) come to mind.

**Comment by TylerHelmuth** [comment]
@codeboten what problem does renaming the exporter solve?  Are users getting confused thinking that the exporter write to a log?

**Comment by codeboten** [comment]
This issue was raised as a result of the discussion in the SIG call 3 weeks ago to decide whether or not to rename the exporter. Based on the history in https://github.com/open-telemetry/opentelemetry-collector/issues/3524, I would say we should not to this, specifically the comment here: https://github.com/open-telemetry/opentelemetry-collector/pull/3609#pullrequestreview-705486043

My vague memory from the discussion in the call was whether we need to rename it before changing its status. If we agree that `logging` is good enough, then we can avoid doing the work here.

**Comment by jpkrohling** [comment]
Logging is confusing as, in the context of the collector, we have a logs pipeline and a logging exporter. I've seen users confused by that. During the SIG call, I remember folks also wanting to get compatibility rules for the output being generated by the logging exporter, meaning that they intend to rely on that, and they really shouldn't. 

Renaming it to `debug` will make it clear what the exporter really is about.

**Comment by mx-psi** [comment]
If we are going to rename it, I would go with `debug`. But to be frank, I don't see a future where we can get rid of the `logging` name with the tools we have today, the experience with #6334 shows that our users take a significant amount of time to update and adapt to deprecations. I think realistically the question is: are we willing to have to maintain compatibility with both names forever to do this change?

Personally, while I appreciate the arguments being made, I am starting to think that it's better if we keep things as is and don't do the renaming: it seems like the price to pay is too high.

**Comment by astencel-sumo** [comment]
> If we are going to rename it, I would go with `debug`.

I second that. If I saw a `stdout` exporter, I would think "oh, so like `file` exporter, but to stdout". If we make this change, we want to emphasize that this is a debugging tool, not a tool to export logs to a console or to `stdout` in a format anyone might want to rely on.

I agree this is a change that's easy to dismiss as it is not a "feature" and it carries a lot of cost.

At the same time, I believe that good names make a lot of difference. They make products more user friendly, especially to new users. Confusing names (can we agree that `logging` is a confusing name?) make onboarding harder and add to the cognitive load, making the learning curve steeper. The more quirks like this, the less pleasant it is to use the product also in the long run.

My recommendation is to mark the `logging` exporter as deprecated and leave it there for a year, maybe two years. I would copy its code and create a separate `debug` exporter that can then be independently developed, without making any changes to the deprecated code.

This will take a lot of time, but in two years, everyone will be hopefully using `debug` exporter and the world will be a tiny bit ~~less awful~~ better :wink:

**Comment by codeboten** [comment]
Maybe voting on this is the best way to move forward? It feels like we could be stuck in this discussion for a long time without anything actionable resulting from it :) I would like to call out that at least one other language (java) calls the debug/stdout exporter a logging exporter as per the issue in the spec [here](https://github.com/open-telemetry/opentelemetry-specification/issues/1931#issue-998620480).

What should we do with this exporter?

🚀 nothing, leave the `loggingexporter` as is and close this issue as a reference of the decision
🚢 rename to `debugexporter` and leave the logging exporter as deprecated for 1 year
👀 improve the `loggingexporter` to support additional functionality like allowing users to decide on the output format

**Comment by jmacd** [comment]
E.g., of additional functionality in the contrib `fileexporter` https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22079
