### ISSUE TITLE
`otelctl` CLI tool to verify the config file

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-collector#7962]
**Is your feature request related to a problem? Please describe.**

I started working with Collector configuration files a lot. Many components have a non-trivial number of configuration settings (in contrib distribution). The rules for valid configuration are not very obvious to the end user. And there is no way to validate the config files in CI systems, leaving the only option to run and verify manually. I want to propose a `otelctl` with a check command which validates configuration files. I believe this will be useful for teams that work with the Collector service.

**Describe the solution you'd like**

A command line tool, `otelctl`, to validate the configuration files.

**Describe alternatives you've considered**

Running collector service and manually verifying

**Additional context**

There will likely be specific errors that can't be covered. However, having a tool that catches as many errors as possible is better than having nothing. Perhaps this could be extended to for more use-cases for working with collector service.

I will be happy to work on this and contribute.

**Comment by mx-psi** [comment]
I think this should be builtin into the Collector binary, since validation is specific to each Collector distro. For example, the validation done for the OpenTelemetry Collector core distro would be different to that of the OpenTelemetry Collector contrib distro  (since there are components in the latter that are not present in the former). And the user cannot specify their distro in general, since users can have custom Collector distributions.

If you are up for opening a PR, this validation would consist of unmarshaling and then calling the `Validate` method [here](https://github.com/open-telemetry/opentelemetry-collector/blob/5abb16723ff13e122f416770d167c972adc35fb2/otelcol/config.go#L44).

**Comment by codeboten** [comment]
`otelcol validate` should already address this issue, if it doesn not, it should be improved :)

**Comment by srikanthccv** [comment]
Thank you, @codeboten. I will close this issue since it already exists. Will open new issues for any potential enhancements.
