### ISSUE TITLE
Forcing a request to be traced

### ISSUE THREAD

**Issue by mre** [open-telemetry/opentelemetry-collector#898]
Google Cloud Trace has an option to [force tracing a request](https://cloud.google.com/trace/docs/setup#force-trace). Is there something similar for OpenTelemetry?

**Comment by bogdandrutu** [comment]
Sorry @mre this is something that belongs to https://github.com/open-telemetry/opentelemetry-specification not here, since is about the libraries (if I understand correctly).

Please file the issue in that repo with a bit more details about what you try to achieve. If this is related to the collector feel free to reopen.
