### ISSUE TITLE
Add Container/K8s Metrics Receivers

### ISSUE THREAD

**Issue by mxiamxia** [open-telemetry/opentelemetry-collector#916]
Can we add the receivers which can collect Container metrics within OTel collector? 

For example, we can create the receiver wraps with cAdvisor to collect container metrics in the receiver and pass it into Collector pipeline all the way to the backend instead of running cAdvisor in a separate container instance to do that. Also, another similar receiver can be added for Kubernetes by calling k8s apiserver.

**Comment by pmcollins** [comment]
Hi @mxiamxia -- we are working toward providing container metrics via the Kubelet API in a cAdvisor independent way (because cAdvisor as a source of metrics from Kubelet has been deprecated -- https://kubernetes.io/docs/setup/release/notes/#kubelet ).

There's a Kubelet stats receiver in progress here:
https://github.com/signalfx/opentelemetry-collector-contrib/pull/4
that will send relevant container metrics down the pipeline. Please feel free to add any suggestions!

**Comment by mxiamxia** [comment]
@bogdandrutu, @pmcollins   Thanks for sharing the info. I'd love to do if anything I can contribute to the community. I'll keep checking the progress on this and give my feedback and PR when I can. Thanks.
