### ISSUE TITLE
[config/confighttp] `IncludeMetadata` is experimental

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector#9381]
From confighttp.go:

```
// IncludeMetadata propagates the client metadata from the incoming requests to the downstream consumers
// Experimental: *NOTE* this option is subject to change or removal in the future.
IncludeMetadata bool `mapstructure:"include_metadata"`
```

**Comment by TylerHelmuth** [comment]
The origin of the `Experiment` designation is [here](https://github.com/open-telemetry/opentelemetry-collector/pull/4547#discussion_r779812787). 

On one hand it has been 2 years and requests to include only certain headers has not surfaced. The feature has been working as needed via the `headerssetterextension` since v0.58.0 (August 2022).

On the other hand, the API still doesn't let us add this feature in the future without either doing a breaking change or adding a new section, which spreads the feature out between 2 root configuration options.

Changing this now would end up being a user-facing configuration breaking change, not only an API breaking change.  Seeing as we haven't had user requests for this feature I am against removing `IncludeMetadata` so close to stability. If, after a 1.0 release, a specific need to filter headers arises, we could add a new configuration interface and deprecate `IncludeMetadata`.  Then we could remove `IncludeMetadata` in an eventual 2.0 release.

We _could_ lean on the `Experimental` flag to deprecate `IncludeMetadata` now, add a new configuration interface, and remove `IncludeMetadata` either before 1.0 or after 1.0, but I don't think that would be a good end-user experience.

**Comment by mx-psi** [comment]
I would vote for stabilizing the `client` module before we decide on this

**Comment by jsirianni** [comment]
We (observIQ) are using this and have a customer using it as well. It would be great if `include_metadata` could be kept around.

**Comment by atoulme** [comment]
> Related: client lists [`client.Info.Metadata`](https://github.com/open-telemetry/opentelemetry-collector/blob/4ae8d2bcd5ae2e72280fb6af7e9402b7b6e7c6cb/client/client.go#L100-L102) as experimental from the same PR. Whether or not we stick with the `IncludeMetadata` config interface I think `client.Info.Metadata` is here to stay. I think we could safely drop the `Experimental` warning from that struct.

I agree, since it's no longer experimental on `client`, it should no longer be experimental in `confighttp` and `configgrpc`.
