### ISSUE TITLE
[component] Review `component.Host.GetFactory`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#9511]
`component.Host.GetFactory` is used by a single component: the receivercreator. While it may not be possible it would be great to consider if we can remove this or maybe make it optional (by having an optional interface that the service can implement). This would simplify the `Host` interface

**Comment by mx-psi** [comment]
One example where we do the optional interface https://github.com/open-telemetry/opentelemetry-collector/blob/91f13c309d00eef5b997a2e810effb2a4ccd95d4/extension/zpagesextension/zpagesextension.go#L58-L66

**Comment by TylerHelmuth** [comment]
Removing it from the `component.Host` interface and leaving it implemented on our implementation of `component.Host` seems fine to me.

On the other hand, the functionality is interesting and simple for any `component.Host` to implement, since it should already have all the component factories it is managing. Unlike https://github.com/open-telemetry/opentelemetry-collector/issues/7370 where `connectors` were the clear solution to components needing to call `GetExporters`, this method is the only way for 1 component to create another.

Since we only have 1 use case that utilizes this feature, I am in favor of the optional interface approach, but would be ok if we choose to keep it on the interface.

**Comment by atoulme** [comment]
I think we could change the behavior so that the `GetFactory` method is available as a func as a receiver factory option. I'll try and draft something for review.

**Comment by atoulme** [comment]
Here is the draft PR with a design experiment: https://github.com/open-telemetry/opentelemetry-collector/pull/10679

I changed the design a bit so you can only get access to receiver factories, hopefully that's fine given the only use case we have is about creating receivers.

**Comment by mx-psi** [comment]
I think #10679 is interesting, but it also seems like something we can do after 1.0. If we are okay with removing this from `component.Host` and keeping on `service`, I think that's the bare minimum we can do now and we can look into something like #10679 afterwards
