### ISSUE TITLE
Log Collection Proof of Concept: Validate Collector can control FluentBit

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#956]
We want to validate that FluentBit can be controlled by OpenTelemetry Collector.

The following needs to be done:

- [ ] Clarify and design how Collector can control the lifecycle of the
  FluentBit (start/stop/restart?). Only implement parts that require
  clarification via experimentation.
- [ ] Design how log collection configuration can be specified in Collector
  config file, how it can be transformed to FluentBit config and passed to
  FluentBit. We don't need to implement this, we need a spec that shows it is
  viable.

**Comment by josephflynch** [comment]
Google is soon going to start design on the Master Agent (likely written in Go) as we've discussed in past.  Our intention is for it to ultimately control Fluentbit, Collectd and OT collectors (such as the emerging Windows agent, SignalFx port, trace agent, etc.).  We intend for it to be open source and it could in theory be built on Collector framework (as we presented to SIG a few months back) although I'm not certain there will be a material benefit to this.  We could share the design doc if it'd be helpful.

**Comment by PettitWesley** [comment]
> Clarify and design how Collector can control the lifecycle of the
FluentBit (start/stop/restart?)

It's possible I'm missing something... but I think this is pretty simple. If you have a Fluent Bit executable, you can invoke it to start. You can pass the FB process a SIGTERM when you want to stop it, and it will flush all logs and then quit. If it gets stuck, you can force it to quit with a SIGKILL. Restarting is just stopping + starting.

> Design how log collection configuration can be specified in Collector
config file, how it can be transformed to FluentBit config and passed to
FluentBit.

So Fluent Bit uses an ini like config file format. For example:

`
[INPUT]
    Name        tail
    Path        /var/log/syslog

[FILTER]
   Name aws
   Match *

[OUTPUT]
    Name   stdout
    Match  *

[OUTPUT]
    Name   forward
    Match  *
    Host 127.0.0.1
    Port 24224
`

Incoming logs are tagged, and the `Match` patterns determine which outputs/filters process which logs. This is similar to the "pipelines" concept that the collector has. It is not the same though. As I understand it, pipelines in the Collector mean that all data from one input is sent to the defined outputs. In Fluent Bit, this is not necessarily the case, since Tags can be dynamic. The tag for a `Tail` input can be dynamic based on the filename. This means that the logs read by a single Tail input can be split between multiple outputs or filters. 

**Can we create a mapping between Collector config and Fluent Bit config?**

The simplest idea would be to say that you just use the Collector YAML schema. Log receivers in the Collector schema become FB inputs, Processors become filters, and exporters become outputs. And Pipelines define the match patterns.

That almost works, except for the issue I noted above that pipelines and FB tag matching do not behave in quite the same way, and FB tag matching seems to be more powerful. Unless I have misunderstood how pipelines work?

**Comment by tigrannajaryan** [comment]
> > Clarify and design how Collector can control the lifecycle of the
> > FluentBit (start/stop/restart?)
> 
> It's possible I'm missing something... but I think this is pretty simple. If you have a Fluent Bit executable, you can invoke it to start. You can pass the FB process a SIGTERM when you want to stop it, and it will flush all logs and then quit. If it gets stuck, you can force it to quit with a SIGKILL. Restarting is just stopping + starting.

Yes, that's mostly it. I am not sure if we want to monitor FB process and restart it if it stops/crashes unexpectedly. Probably not needed for PoC.

**Comment by tigrannajaryan** [comment]
>Incoming logs are tagged, and the Match patterns determine which outputs/filters process which logs. This is similar to the "pipelines" concept that the collector has. It is not the same though. As I understand it, pipelines in the Collector mean that all data from one input is sent to the defined outputs. In Fluent Bit, this is not necessarily the case, since Tags can be dynamic. The tag for a Tail input can be dynamic based on the filename. This means that the logs read by a single Tail input can be split between multiple outputs or filters.

I don't think there is a need to support multiple FluentBit pipelines when it is run by Collector. I think we can configure Fluentbit to have a single output that goes to Collector's FluentBit receiver. Inside the Collector we can then attach this receiver to multiple pipelines if needed.

So, basically one "fluentbit" receiver in the Collector will run one FluentBit process. It is probably going to be very rare that one will need multiple "fluentbit" receivers but that still should be technically possible although will come with an overhead of running multiple FluentBit processes. I think this is fine for PoC.

**Comment by tigrannajaryan** [comment]
>The simplest idea would be to say that you just use the Collector YAML schema. Log receivers in the Collector schema become FB inputs, Processors become filters, and exporters become outputs. And Pipelines define the match patterns.

I think this complicates things. I was thinking of an approach where the entire FB config is specified via one "fluentbit" receiver in the Collector config. Basically we would only aim to do minimal processing in FB process, only what is not possible to efficiently perform in the Collector. The rest of the processing will be in the Collector processors.

This way we would only need to specify and map FB input configs in "fluentbit" receiver section in the Collector. We could try to do one-to-one mapping from yaml to ini:

```yaml
receivers:
  fluentbit:
    input:
      Name: tail
      Path: /var/log/syslog
```

[OUTPUT] section will be automatically generated and appended by "fluentbit" receiver which can even find an unused port for forward protocol dynamically.

**Comment by PettitWesley** [comment]
> I don't think there is a need to support multiple FluentBit pipelines when it is run by Collector...

@tigrannajaryan I mostly agree. I worry though that the Collector's pipeline concept isn't ideal for some advanced logging use cases. Its probably fine for now but may need to be expanded in the future.

Selfish plug, I wrote an entire blog post on advanced log pipeline use cases with Fluentd and Fluent Bit: [Splitting an application’s logs into multiple streams: a Fluent tutorial.](https://aws.amazon.com/blogs/opensource/splitting-application-logs-multiple-streams-fluent/)

There are a few cases where Fluent Bit and Fluentd's tagging feature is convenient:
1. When you tail log files (ex K8s), the tag can become the log file or path name. This is nice because each log file will be from a different app/system, and you might want different processing rules for each, even though you will only have one Tail input/receiver. The most common use case is to apply different regular expression parsers (apache, nginx, envoy, etc) to each log file. I'll add on this that a log file Tail receivers NEEDs to be able to read many different log files. I once worked with a log agent that made you independently configure an input for each log file, and it was hell.
2. Building on the above, in some logging outputs/exporters you will want to differentiate which file the logs came from. In Amazon's case, we have two levels of buckets (groups and streams) that you can put logs in, and in Fluent Bit and Fluentd the tag can be used to name these. I do not actually think this will be a problem with OT if the collector can get the logs in the OT Log Data format nicely- you can probably get this info in the `resource` field and build exporters that use it.
3. The more advanced cases I talk about in that blog. Basically, you have a single input stream of logs coming from one app, but you want to split out some of them to a separate pipeline for different processing and different export destination. With the OT Log data model, this could become very interested because the logs will be so structured- I can imagine building routing rules based on the values of the different fields. These use cases are niche and somewhat rate; but real folks care about them. I wrote that blog after several people reached out to me asking for help solving those sorts of cases, so that I wouldn't have to keep re-explaining.
4. Aggregator/Service Use Cases. You run the Collector as a centralized service, with many other collectors/agents/processes forwarding data to it from other hosts. Fluentd is commonly run this way for logs, and have fairly complicated routing based on source and content of the logs is common. You'll have logs from a ton of apps ingested on one input/receiver, but then you'll want to forward them to different processors and exporters.

**Comment by PettitWesley** [comment]
> I was thinking of an approach where the entire FB config is specified via one "fluentbit" receiver in the Collector config. Basically we would only aim to do minimal processing in FB process,

@tigrannajaryan Ok, that's easy then. I recommend that we use the inputs and the regex parsing capabilities of Fluent Bit. When it grabs legacy logs from Files and other sources, they won't be nicely formatted, the default for files is:

```
{
    "log": "the actual log line read from the file..."
}
```

If the log can be parsed with a regex (ex envoy, nginx, apache) into a JSON object with nicely named fields, it should be easier to then get it into the OT Log Schema.

Doing that parsing in Fluent Bit should be slightly more performant that doing it in the collector. Once Fluent Bit implements generic multiline log processing, you might want to use that as well, because its a fairly common use case which is resource intensive and would be time consuming to implement in the collector.

**Comment by PettitWesley** [comment]
For the receiver schema, I see what you're thinking, I think that works, the only question is whether support for configuring parsers should be added too.

**Comment by tigrannajaryan** [comment]
> Selfish plug, I wrote an entire blog post on advanced log pipeline use cases with Fluentd and Fluent Bit: [Splitting an application’s logs into multiple streams: a Fluent tutorial.](https://aws.amazon.com/blogs/opensource/splitting-application-logs-multiple-streams-fluent/)

@PettitWesley The link does not open for me.

**Comment by PettitWesley** [comment]
@tigrannajaryan weird... it does for me even in your quoted message, here is the URL: https://aws.amazon.com/blogs/opensource/splitting-application-logs-multiple-streams-fluent/

**Comment by tigrannajaryan** [comment]
Works for me now.

**Comment by keitwb** [comment]
This is more or less implemented in https://github.com/open-telemetry/opentelemetry-collector/pull/1381.

**Comment by bogdandrutu** [comment]
@keitwb I think this issue is close, but @josephflynch your generic framework is still something that we are interested in, and we should switch the current extension to that framework once available.

**Comment by bogdandrutu** [comment]
Closing this issue since just the fluentbit is ready, but @josephflynch please start a new issue for the more generic framework that you proposed.

**Comment by tigrannajaryan** [comment]
This is indeed done in #1381 as far as PoC is concerned. We may make further improvements but that can be done in separate issues/PRs.
