### ISSUE TITLE
When multiple goroutine calls consume, mb.newShard(md) will be called multiple times.

### ISSUE THREAD

**Issue by luyuanx2** [open-telemetry/opentelemetry-collector#9739]
**Describe the bug**

The problematic code is as shown below:
![image](https://github.com/open-telemetry/opentelemetry-collector/assets/26129033/2bf2de19-99dd-4c18-ba22-7f373c02e453)

**Steps to reproduce**

Here is a simple code showing this bug:
```go
package main

import (
	"fmt"
	"sync"
	"time"
)

type multiShardBatcher struct {
	batchers sync.Map

	lock sync.Mutex
	size int
}
type shard struct {
}

func (mb *multiShardBatcher) newShard() *shard {
	b := &shard{}
	fmt.Println("new shard")
	time.Sleep(1 * time.Second)
	return b
}

func (mb *multiShardBatcher) consume(key string) *shard {

	b, ok := mb.batchers.Load(key)
	if !ok {
		mb.lock.Lock()
		b, _ = mb.batchers.LoadOrStore(key, mb.newShard())
		mb.lock.Unlock()
	}
	return b.(*shard)
}

func main() {

	mb := &multiShardBatcher{}

	group := sync.WaitGroup{}
	for i := 0; i < 10; i++ {
		group.Add(1)
		go func() {
			mb.consume("key")
			group.Done()
		}()
	}
	group.Wait()

}
```

<img width="795" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector/assets/26129033/2490256d-3043-47d2-9a6b-f24fa056603c">

**What did you expect to see?**

**What did you see instead?**

**What version did you use?**

**What config did you use?**

**Environment**

**Additional context**

**Comment by mx-psi** [comment]
cc @dmitryax

**Comment by astencel-sumo** [comment]
This report looks valid to me. The `mb.newShard(md)` method not only creates a new shard, but also starts a new goroutine on it, so we should not be doing that if we might not keep the shard around (which is what happens when the shard had already been created in another goroutine). Otherwise we end up with a goroutine leak.

We should move `mb.lock.Lock()` to before the initial `mb.batchers.Load(aset)`.

This code was introduced in https://github.com/open-telemetry/opentelemetry-collector/pull/7714. @bogdandrutu can you take a look?

cc @jmacd as the original contributor of the feature (https://github.com/open-telemetry/opentelemetry-collector/pull/7578).

**Comment by astencel-sumo** [comment]
Proposed a fix for this in https://github.com/open-telemetry/opentelemetry-collector/pull/9814.
